### ISSUE TITLE
Json 转JavaBean

### ISSUE THREAD

**Issue by CherryLover** [hongyangAndroid/wanandroid#10]
1. 在成功转成JavaBean之后右侧的文本框的大小还是比较合适的，当鼠标点上去的时候，文本框就自动缩小了；
2. 如果 Json 过长，转成JavaBean 的之后就会出现 JavaBean 里的方法和参数不完整。

**Comment by hongyangAndroid** [comment]
可以贴一下，json字符串吗？我周末测试下，顺带修复下

**Comment by CherryLover** [comment]
抱歉，那个 Json 字符串我没找到，不过又发现了 这个小工具的一个小 bug：
3. 不能进行第二次转换，点击清空之后，将新的 Json 字符串填入，再次转 JavaBean 显示的结果还是之前的。

网站建议：

可以让大家都来投稿，但不是一股脑的塞进来，把大家推送的文章归到单独的一类，然后在首页的时候向读者进行随机推送，让读者阅读完之后进行评价或是打分。同一篇文章达到一定的程度之后（符合大部分读者的需求之后）再加入到现有的文章体系中。这个类似于向杂志社投稿，你可以参考一下，不过这个工作量有些大了。我感觉我给你挖了一个大坑？

**Comment by hongyangAndroid** [comment]
有没有使用浏览器相关信息~  
通过chrome,safari3个问题均未复现。

**Comment by CherryLover** [comment]
根据你的提示，我仔细检查了一下我的Chrome，发现有个检查英文写作纠错工具的插件：Grammarly for Chrome。我把他关闭之后就没有出现过之前的问题了。真的非常抱歉。

**Comment by hongyangAndroid** [comment]
ok
