### ISSUE TITLE
Todo 优先级建议

### ISSUE THREAD

**Issue by xujiaji** [hongyangAndroid/wanandroid#100]
todo API是否可以添加一个优先级功能呢？正在进行中的todo，如果有优先级进行排列与区分，可以让做的事情更加有条理些

**Comment by hongyangAndroid** [comment]
可以，我可以加一个int字段表示优先级，然后客户端可以根据自己的喜好，定义一些类别：

紧急：1 ， 一般：2 ，无所谓：3 ....

提交的时候转化为数字即可。

预计周末开发。  有其他建议，欢迎指出

**Comment by xujiaji** [comment]
嗯，是这样的。其他的建议话可能不是那么重要

比如说：有些任务可能是每日、每工作日、每周任务...
假设有周期属性`cycleType`
- `cycleType = 1` 每日重复任务，当设置为完成时，新建同个任务时间改为明天
- `cycleType = 2`  每工作日任务，当设置为完成时，新建同个任务时间改为下个工作日
- `cycleType = 3`  每周任务，当设置为完成时，新建同个任务日期到下周一
:joy: 这个可能不是那么必要哈

**Comment by hongyangAndroid** [comment]
[#98] todo v2发布，已经支持优先级。

**Comment by xujiaji** [comment]
更新接口，标题、内容和时间可更新。分类和优先更新无效
![image](https://user-images.githubusercontent.com/16447251/49336275-f17efc00-f639-11e8-8b53-e3f1786d4879.png)

**Comment by hongyangAndroid** [comment]
已修复，可以再测试下。

**Comment by xujiaji** [comment]
嗯，可以了哦
