### ISSUE TITLE
Todo接口2.0根据type=0查询，返回的是全部

### ISSUE THREAD

**Issue by AbleZ** [hongyangAndroid/wanandroid#105]
http://www.wanandroid.com/lg/todo/v2/list/1/json?type=0，返回的是全部的数据，没有过滤

**Comment by hongyangAndroid** [comment]
#98 

![image](https://user-images.githubusercontent.com/10704521/50883884-50e3df00-1424-11e9-9af7-e5c0823b21b2.png)

尽可能使用大于0作为分类吧。

**Comment by AbleZ** [comment]
![image](https://user-images.githubusercontent.com/24488772/50887155-64477800-142d-11e9-87ee-93a3f24f5a20.png)
没有从1.0版本跳出来，谢谢解答
