### ISSUE TITLE
关于更新TODO，能否新增更新completeDate的功能？

### ISSUE THREAD

**Issue by d745282469** [hongyangAndroid/wanandroid#106]
打算用TODO接口做一个本地的APP，但是发现如果APP处于无网络状态，完成TODO的话会无法更新状态，所以我的想法是：如果无网络，则先在本地数据库中记录完成时间，当检测到网络连接时再通知服务器更新。不知道是否有纰漏？

**Comment by d745282469** [comment]
网站的API文档没提到可以传completeDate呀？


http://www.wanandroid.com/lg/todo/update/83/json

方法：POST
参数：
	id: 拼接在链接上，为唯一标识，列表数据返回时，每个todo 都会有个id标识 （必须）
	title: 更新标题 （必须）
	content: 新增详情（必须）
	date: 2018-08-01（必须）
	status: 0 // 0为未完成，1为完成
	type: ；
	priority: ；

**Comment by hongyangAndroid** [comment]
done,update 两个接口添加了completeDate参数，格式为 yyyy-MM-dd，更新完成时间。

**Comment by d745282469** [comment]
谢谢鸿神。
