### ISSUE TITLE
【wanandroid】bug汇总：记录问题，解决方案。

### ISSUE THREAD

**Issue by hongyangAndroid** [hongyangAndroid/wanandroid#11]
1. 用户名无法使用中文

**Comment by hongyangAndroid** [comment]
1.用户名无法使用中文 fixed

**Comment by hongyangAndroid** [comment]
2. 搜索时，关键词中间使用多个空格间隔。
现象:转发次数过多，导致错误。

原因是：做空格分隔的时候，以单个空格做分离的，造成多个空格时sql错误。
错误默认跳转首页的，而因为搜索携带了k参数，会被首页分发到搜索，造成一直递归的请求的转发。

目前已经修复~

**Comment by hongyangAndroid** [comment]
3. 无法自动登录。
现象：登录后，关闭浏览器，再打开，登录状态丢失。

原因：存储cookie时setMaxAge未设置，中英文存储转码那块也有些逻辑问题。

目前已经修复~

**Comment by hongyangAndroid** [comment]
![image](https://user-images.githubusercontent.com/10704521/35957142-eed8d3f8-0cd4-11e8-95ce-df30e900dedf.png)
![image](https://user-images.githubusercontent.com/10704521/35957153-fc720930-0cd4-11e8-87db-f369182098b2.png)
两个地方都可以编辑呢，如果你那有问题，可能是兼容性问题，提供下浏览器和版本号，thx~

后续会考虑新增排序功能。

**Comment by chuwe1** [comment]
Chrome最新版本

**Comment by xks19943** [comment]
取消收藏的时候没有更新统计数据
