### ISSUE TITLE
注册失败的问题又出现了

### ISSUE THREAD

**Issue by rainshine1190** [hongyangAndroid/wanandroid#112]
<html><head><title>Apache Tomcat/7.0.77 - Error report</title><style></style> </head><body><h1>HTTP Status 400 - </h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>The request sent by the client was syntactically incorrect.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.77</h3></body></html>

我的注册数据：{"username":"liangchao","password":"12345678","repassword":"12345678"}

**Comment by hongyangAndroid** [comment]
400的错误，需要检查你这边请求发出格式等，建议先通过postman 模拟。

**Comment by rainshine1190** [comment]
好的，多谢，是我请求数据格式问题，已解决
