### ISSUE TITLE
内存泄漏隐患

### ISSUE THREAD

**Issue by 123456789lgj** [hongyangAndroid/wanandroid#113]
allActivities.add(act); 这段代码我认为是有内存泄漏隐患的，如果退出activity的过程中没有走ondestroy方法的话是不是有隐患？大神您认为呢？

**Comment by hongyangAndroid** [comment]
所有的开源app都是由其他开发者开发的，需要到指定的仓库提issue，本仓库主要记录wanandroid 网站，以及开放api的问题。
