### ISSUE TITLE
TODO登录态丢失

### ISSUE THREAD

**Issue by Kbaseczy** [hongyangAndroid/wanandroid#115]
app内登陆已经做好，登陆后进入TODO没有记录，查看返回的数据-->errMSG:"请先登录"
这个登录态为啥没有获取到呢，同样的收藏也需要登陆态可以正常显示数据。

**Comment by hongyangAndroid** [comment]
check下，登录后需要持久化cookie。

网站的登录和收藏的接口与开放api调用的是同一个接口，可以直接拿网站查看网络，观察接口数据传递，重点关注cookie。

**Comment by dgliangg** [comment]
我猜你没有把http改成https，我刚才也遇到了，然后看到前面说接口升级了，我试了https成功了。

**Comment by Kbaseczy** [comment]
> 我猜你没有把http改成https，我刚才也遇到了，然后看到前面说接口升级了，我试了https成功了。

TODO这个，在升级为https之前我就写好了，提示未登录。请问下你做了持久化cookie了吗

**Comment by Kbaseczy** [comment]
> 我猜你没有把http改成https，我刚才也遇到了，然后看到前面说接口升级了，我试了https成功了。

TODO这个，在升级为https之前我就写好了，提示未登录。请问下你做了持久化cookie了吗

**Comment by dgliangg** [comment]
登录后会返回cookie信息，保存这个信息，你请求todo、收藏等接口时把cookie加入到header就可以了
