### ISSUE TITLE
关于注册接口Content-Type 问题

### ISSUE THREAD

**Issue by mirse** [hongyangAndroid/wanandroid#118]
![image](https://user-images.githubusercontent.com/5188922/54736519-6294f000-4be6-11e9-8a89-e2d16a77bdd8.png)

使用'Content-Type':"application/json"，发送后返回的error是：
SyntaxError:Json Parse error：Unrecognized token '<',
是哪个参数用错了吗？

**Comment by hongyangAndroid** [comment]
目前整个站点Api没有使用application/json 发送参数给服务端的。 都是普通的post请求，或者form post。

**Comment by mirse** [comment]
![image](https://user-images.githubusercontent.com/5188922/54738508-8577d200-4bef-11e9-9776-f45f17e3f7d6.png)
我用postman模拟访问，Content-Type咋是application/json;charset=UTF-8？

**Comment by hongyangAndroid** [comment]
这个是response headers

![image](https://user-images.githubusercontent.com/10704521/54738670-29617d80-4bf0-11e9-83d5-80fd0330c047.png)

**Comment by mirse** [comment]
感谢，就是请求body得用表单格式，
![image](https://user-images.githubusercontent.com/5188922/54739968-dccc7100-4bf4-11e9-86f0-c90b51531249.png)
但是header不设置也可以，这怎么理解呢

**Comment by hongyangAndroid** [comment]
不用单独设置，默认的post form会帮你设置header； 你可以抓包看这次请求，是有request header的。

**Comment by mirse** [comment]
3Q
