### ISSUE TITLE
注册接口返回‘用户名已经被注册!’

### ISSUE THREAD

**Issue by kangliangup** [hongyangAndroid/wanandroid#119]
您好，麻烦帮忙看下，调用注册接口，换了好多用户名试了，都提示‘用户名已经被注册’

![8909E633-5CA9-4180-A1D4-122FA7461616](https://user-images.githubusercontent.com/23203925/54756753-d30e3200-4c23-11e9-93b9-22f6dad534ff.png)

**Comment by hongyangAndroid** [comment]
网站右上角的注册功能，和开放API使用的相同的接口，可以试下，是正常哒。

**Comment by kangliangup** [comment]
谢谢大神了，是我自己参数传错了
