### ISSUE TITLE
个人类型小程序无法使用web-view加载文章详情页面

### ISSUE THREAD

**Issue by WuMaoQiang** [hongyangAndroid/wanandroid#121]
我是个人类型的小程序想完成一个小程序端的wanAndroid，到文章详情就是一个web页。可是个人类型无法使用web-view组件，麻烦问一个各位有什么方式能把页面显示出来吗？因为文章详情是重点模块，如果没法显示 那便没意义了

**Comment by hongyangAndroid** [comment]
目前还没什么办法...

建议使用todo的api，完全是https。
