### ISSUE TITLE
关于cookies持久化的问题 

### ISSUE THREAD

**Issue by liguangze** [hongyangAndroid/wanandroid#122]
我在小程序中登录成功后，返回的信息

![image](https://user-images.githubusercontent.com/10549682/55540669-02c63b00-56f6-11e9-8fdb-6506464ed8ae.png)

cookies 是一个集合，我应该拿着那个去做持久化呢，第一次做小程序的持久化，不太理解
    header: {
        'content-type': 'application/x-www-form-urlencoded',
         'cookie': "SESSID=" + wx.getStorageSync("sessionid")
      },

这里面传值的时候cookies不应该是一个具体的值吗，我应该传哪个，求指教

**Comment by hongyangAndroid** [comment]
可以参考下这个 https://github.com/mtjsoft/wanandroid  ，已经上线的小程序~

**Comment by liguangze** [comment]
他的这个我看下，也没有做cookies持久化，只是添加收藏后，把文章的id存在了本地，

**Comment by hongyangAndroid** [comment]
那就有点尴尬了...小程序这块我不太熟悉。

顺手搜了一篇：

https://blog.csdn.net/DylanCat/article/details/78186427

**Comment by liguangze** [comment]
嗯，谢谢了，我也是刚刚入手小程序，
这个搜到了，问题还是我截图的，登录成功后返回的是个集合，我该保存哪个，我把整个cookies都保存了，然后按照这个
header: {
'content-type': 'application/x-www-form-urlencoded',
'cookie': "SESSID=" + wx.getStorageSync("sessionid")
},传过去，
行不通

**Comment by hongyangAndroid** [comment]
response返回的时候，cookie的key是SetCookies，格式大概是：

![image](https://user-images.githubusercontent.com/10704521/55545081-06aa8b00-56ff-11e9-8432-57bbb63349bc.png)

需要把这里面的cookie都存下来。

请求的时候带上，key是Cookies，值是key=value的形式，大概是：

![image](https://user-images.githubusercontent.com/10704521/55545108-17f39780-56ff-11e9-9909-aa21b0d6b7ef.png)


中间需要做一下转化，值都是有的。

这里有个文章，我仔细看了下，应该没问题：
https://zhuanlan.zhihu.com/p/33586841

**Comment by liguangze** [comment]
OK了，谢谢了，主要是取res.header['Set-Cookie']这里面的值，

**Comment by liguangze** [comment]
![image](https://user-images.githubusercontent.com/10549682/55776511-98cfdc00-5acf-11e9-9766-481ddca13341.png)
大神，收藏接口总是返回false,这个没有具体信息不是收藏成功了吧

**Comment by liguangze** [comment]
@hongyangAndroid   大神，我这个问题还没有解决呢，掉的收藏接口，返回的信息是上图的，data里面数据为null，代表收藏接口调用成功了吗，没有成功吧，在收藏接口已经返回这条数据了，成功了吧，collected的这个字段总是false，

**Comment by liguangze** [comment]
我在网站是试过了，点击收藏成功了，在程序中调用http://wanandroid.com/article/list/0/json这个接口，这个collected字段还是false

**Comment by hongyangAndroid** [comment]
errorcode=0 为收藏成功。  

测试需要在同一个上下文中，不能网站点击收藏，小程序调用首页列表接口这种方式。

**Comment by liguangze** [comment]
我小程序中测试也是一样，返回的上面的数据，调用收藏列表也能返回收藏的数据，但是首页的列表的collected字段就是false,

**Comment by mirse** [comment]
cookie我也一头雾水=-=

**Comment by liguangze** [comment]
cookie现在是没有问题的，就是收藏成功后，返回的总是false
