### ISSUE TITLE
请求没反应

### ISSUE THREAD

**Issue by Ghaker** [hongyangAndroid/wanandroid#124]
curl -d "username=hello1&password=123456&repassword=123456" "http://www.wanandroid.com/user/register"
没有反应，是服务关了，还是我的命令写错了？

**Comment by hongyangAndroid** [comment]
使用https://www.wanandroid.com/user/register , http全部换成https了。

**Comment by Ghaker** [comment]
确实，80端口不管用了，可以转接一下
