### ISSUE TITLE
洋神，发现了个小问题

### ISSUE THREAD

**Issue by ITGungnir** [hongyangAndroid/wanandroid#125]
洋神，今天发现了一个问题：

用户登录以后的response里会返回收藏的文章id列表，

我添加了几篇站外的文章，

然后重新登录，发现response里的collectIds里，站外文章的id都是-1，如图，

![image](https://user-images.githubusercontent.com/18190514/57459990-db3f3100-72a6-11e9-917a-6d43e3bae2a0.png)

这里能不能把-1改成真正的id？

谢谢洋神，洋神辛苦~~

**Comment by hongyangAndroid** [comment]
站外文章，属于该账号下私人收藏的。

不属于整个网站的对外的文章，故没有对应的 id。

不过这个-1 挺奇怪的，可能我是获取的收藏文章列表，直接匹配网站的对外的文章，没匹配到的写的 -1。
