### ISSUE TITLE
mockapi 功能彻底下线

### ISSUE THREAD

**Issue by hongyangAndroid** [hongyangAndroid/wanandroid#128]
曾经有个 MockAPI功能，由于被滥用，已经永久下线。

**Comment by niulinguo** [comment]
好遗憾，今天本来想做一个Demo，需要使用MockAPI，找了半天没找到。

**Comment by Zkp275557625** [comment]
> 好遗憾，今天本来想做一个Demo，需要使用MockAPI，找了半天没找到。

http://mock-api.com/app.html#!/login
