### ISSUE TITLE
分享博文的入口在哪？

### ISSUE THREAD

**Issue by shijiacheng** [hongyangAndroid/wanandroid#132]
洋哥，wanandroid网站能分享博文吗？我没有找到入口，麻烦您告知一下。

**Comment by hongyangAndroid** [comment]
目前还没有这个入口呢

**Comment by shijiacheng** [comment]
> 目前还没有这个入口呢

那怎么分享博文呢？发邮件给您吗？

**Comment by hongyangAndroid** [comment]
https://www.wanandroid.com/user_article 已经上线
