### ISSUE TITLE
Meterail Design风格商城类项目

### ISSUE THREAD

**Issue by xiong751243170** [hongyangAndroid/wanandroid#134]
接口有问题吧。请查看、

**Comment by xiong751243170** [comment]
SocketTimeoutException: connect timed out

**Comment by hongyangAndroid** [comment]
哪个接口？

是指这个商城开源项目的接口么？那issue需要提到这个项目的地址中去

**Comment by xiong751243170** [comment]
嗯。就是那个商城开源项目。您看看。接口是否请求超时。我改回了https。
https://www.wanandroid.com/blog/show/2598   这个项目地址

**Comment by hongyangAndroid** [comment]
这个需要在那个项目去提issue

**Comment by xiong751243170** [comment]
嗯好的。大佬。我看了是请求超时。是否是您那边服务器关闭了呢。

**Comment by hongyangAndroid** [comment]
不是我的服务器... 我这边服务器只托管 wanandroid.com 开头的域名。

wanandroid里面的项目都是开源，都是不同的作者编写的，服务端也不是托管在wanandroid上面。

**Comment by xiong751243170** [comment]
嗯嗯 。明白了 。谢谢




------------------ 原始邮件 ------------------
发件人: "张鸿洋"<notifications@github.com>;
发送时间: 2019年6月19日(星期三) 中午1:19
收件人: "hongyangAndroid/wanandroid"<wanandroid@noreply.github.com>;
抄送: "我是你唯一观众"<751243170@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [hongyangAndroid/wanandroid] Meterail Design风格商城类项目 (#134)




不是我的服务器... 我这边服务器只托管 wanandroid.com 开头的域名。
 
wanandroid里面的项目都是开源，都是不同的作者编写的，服务端也不是托管在wanandroid上面。
