### ISSUE TITLE
建议 加个用户信息接口

### ISSUE THREAD

**Issue by lianshuoshuo** [hongyangAndroid/wanandroid#135]
加个用户信息接口  可以修改自己的一些信息  什么的。。。

**Comment by hongyangAndroid** [comment]
好的，应该是有昵称的需求吧，我准备尽快在 完善个人信息入口，新增昵称这一字段，未来在网站上均已昵称显示。

**Comment by hongyangAndroid** [comment]
![image](https://user-images.githubusercontent.com/10704521/60358119-f9ecb900-9a07-11e9-845a-c78e4e7ece2d.png)

可以填写昵称了。

右上角依然显示用户名，因为只有你自己能看到，其次我担心大家太容易忘记用户名。

问答模块，全部显示昵称，更新昵称后会同步历史问答。

欢迎测试，有问题及时反馈。
