### ISSUE TITLE
todo新接口获取todo列表过滤条件会自动带上status=1

### ISSUE THREAD

**Issue by CCY0122** [hongyangAndroid/wanandroid#138]
我获取todo列表时，只加上了orderby，但返回的列表都是“已完成”的，没有返回“未完成的”todo。我调的接口：https://www.wanandroid.com/lg/todo/v2/list/1/json?orderby=2

**Comment by hongyangAndroid** [comment]
好像确实有这个bug，修复后回复你。

**Comment by hongyangAndroid** [comment]
check 了一下代码，当时确实加了这个逻辑，如果按照完成时间排序，会自动设置 Status=1为完成状态。

目前已经去除该逻辑，半小时后生效。
