### ISSUE TITLE
崩溃退出

### ISSUE THREAD

**Issue by HotBloodMan** [hongyangAndroid/wanandroid#139]
版本号:1.1.1
      使用发现：点击app图标，一进入主界面，迅速切换到“项目”模块下，立马向上滑动，出现崩溃退出现象，多次测试，出现同样的退出现象。

**Comment by hongyangAndroid** [comment]
这个仓库是针对网站的。

所有的App，都是其他作者开源的，需要针对对应作者下提issue。
