### ISSUE TITLE
无法自动登录

### ISSUE THREAD

**Issue by xiaochaodevelop** [hongyangAndroid/wanandroid#14]
我用的谷歌浏览器自动登录不了，我还特意记住密码了。如果谷歌浏览器没有关闭，而是只关闭该网站后再打开不需要重新登录。一旦把谷歌浏览器关了再打开进入该网站就会要重新登录。不知道是不是我浏览器的问题，不过我浏览器也是翻墙下的官方的呀！

**Comment by hongyangAndroid** [comment]
![image](https://user-images.githubusercontent.com/10704521/31851345-bd9e6476-b629-11e7-8193-138fa212529d.png)

[chrome://settings/content/cookies?search=cookie](chrome://settings/content/cookies?search=cookie)

看一哈cookie的设置?

**Comment by xiaochaodevelop** [comment]
![image](https://user-images.githubusercontent.com/28263109/31857629-9e90c9e2-b715-11e7-9062-5a7661ee4e94.png)
cookie设置也是正常的

**Comment by hongyangAndroid** [comment]
换个纯字母的用户名也是这样么，我这边测试还未复现～需要更多信息

**Comment by xiaochaodevelop** [comment]
是的，我用的用户名就是我名字的全拼音

**Comment by xiaochaodevelop** [comment]
![image](https://user-images.githubusercontent.com/28263109/31857659-4f3f1a5a-b716-11e7-87f9-cf4561283dfb.png)
浏览器已经记住密码了，就是每次打开需要重新登录输入用户名

**Comment by hongyangAndroid** [comment]
加一下我QQ ：623565791 , 想办法复现一哈~

**Comment by xiaochaodevelop** [comment]
好的，您同意一下

**Comment by xiaochaodevelop** [comment]
我刚换了个浏览器测了一下，也一样不能自动登录

**Comment by hongyangAndroid** [comment]
fixed ~~~ 感谢~~
