### ISSUE TITLE
同一篇文章调用收藏站内和收藏站外接口都可以成功？

### ISSUE THREAD

**Issue by Meditator-K** [hongyangAndroid/wanandroid#143]
请教大佬几个问题：
1、用哪个字段来区分站内和站外文章呢？
2、同一篇文章，分别调用收藏站内和收藏站外文章，都会返回成功。
3、已经收藏成功的文章，Android端请求首页文章列表时，collect字段依然为false，但是在电脑上登录后在用户中心可以看到收藏的文章。

**Comment by hongyangAndroid** [comment]
1. 站外的文章只会在你自己的收藏列表出现。

2.

收藏站内文章，只需要携带站内文章的id就行了。
 
收藏站外文章，是需要携带标题，作者，链接的。

只要符合上述参数都能成功。

3. 

根据你上面的描述，我估计你是把站内文章，当成站外文章收藏了，即调用了站外收藏文章接口。

注意，收藏站内文章，需要携带文章id即可，文章id由文章列表返回。

可以直接在网站上操作，收藏接口和对外开放接口是同一个。
