### ISSUE TITLE
1. 调用更新 todo 内容的时候，返回列表有 bug；2. todo 列表根据 type = 0 的时候筛选会返回所有数据

### ISSUE THREAD

**Issue by kukyxs** [hongyangAndroid/wanandroid#144]
1. 更新待办内容后，下面是返回的数据截图，当 status = 1 的情况下没有返回完成时间
![bug1.png](https://upload-images.jianshu.io/upload_images/2888797-55483af7b0300c1b.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

2. 进行 todo 条件筛选时候，type = 0 的情况会返回所有的 todo，下面是返回数据截图
![bug2.png](https://upload-images.jianshu.io/upload_images/2888797-3d7326b0d9048260.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by hongyangAndroid** [comment]
根据回复做了如下修改：

问题 1： 当更新 todo，status=1时，会设置 completeDate 为服务器当前时间。
问题 2：

type 需要为大于 0 的整数，如果<=0则无视这个规则。

![image](https://user-images.githubusercontent.com/10704521/62510855-6054ca80-b843-11e9-899e-125315ec4654.png)

恩，稍后修改歧义文档。

**Comment by hongyangAndroid** [comment]
半小时后生效~

**Comment by kukyxs** [comment]
> 半小时后生效~

好的，谢谢洋神~
