### ISSUE TITLE
服务器错误，请反馈给管理员！

### ISSUE THREAD

**Issue by ljiezhou** [hongyangAndroid/wanandroid#146]
今天调试的时候，调用收藏接口，返回这个
 {"data":null,"errorCode":-1,"errorMsg":"服务器错误，请反馈给管理员！"}

**Comment by hongyangAndroid** [comment]
非常感谢支持，我测试收藏《每日一问 butterknife 中的黑科技》复现了错误。

现在已经修复，麻烦帮忙测试再看下，有问题及时反馈。

**Comment by ljiezhou** [comment]
现在测试可以了！
