### ISSUE TITLE
搜索关键词能否搜到文章作者和直接搜索分类名

### ISSUE THREAD

**Issue by wangzailfm** [hongyangAndroid/wanandroid#15]
搜索关键词能否搜到文章作者和直接搜索分类名？？

**Comment by hongyangAndroid** [comment]
感谢建议，考虑添加对分类名搜索，显示在搜索文章顶部。

**Comment by hongyangAndroid** [comment]
![image](https://user-images.githubusercontent.com/10704521/32053627-8334dd14-ba21-11e7-8f09-4e2863e192af.png)
已经增加对分类的搜索，欢迎体验~
