### ISSUE TITLE
导航返回的数据中collect 字段一直为false,就算收藏了这个id也是返回false

### ISSUE THREAD

**Issue by hegaojian** [hongyangAndroid/wanandroid#150]

**Comment by hegaojian** [comment]
![QQ截图20190826173634](https://user-images.githubusercontent.com/18655288/63681367-3847fe00-c828-11e9-81b9-182ee4b4b333.png)
![QQ图片20190826173704](https://user-images.githubusercontent.com/18655288/63681374-3c741b80-c828-11e9-87e5-9433fed6ddd7.png)

**Comment by hegaojian** [comment]
我在所有的请求头 都加了cookies的

**Comment by hongyangAndroid** [comment]
可以直接在浏览器上登录，收藏，然后访问json的url的，看下返回数据是否是false。

**Comment by hegaojian** [comment]
我刚用了Postman请求收藏列表，返回的数据中有导航数据里面的id，在玩安卓网站收藏中也有那条数据，但是请求导航里面的数据确实都是返回 false 
![QQ截图20190827092904](https://user-images.githubusercontent.com/18655288/63734096-7dfada00-c8ad-11e9-91f8-51d0e9bbda3b.png)
![QQ截图20190827093009](https://user-images.githubusercontent.com/18655288/63734101-80f5ca80-c8ad-11e9-9485-7cf48723410c.png)

**Comment by hongyangAndroid** [comment]
明白了，文章收藏是正常的，是吧？

导航返回的 json 数据收藏状态有问题，我看了下，导航返回的数据确实没有考虑收藏的这个功能。

是有这个功能的需求吗？我可以添加

**Comment by hegaojian** [comment]
嗯嗯，是的，现在是有这个需求，谢谢大佬添加

**Comment by hongyangAndroid** [comment]
已经上线，欢迎测试

**Comment by hegaojian** [comment]
老大，刚测试了一下，有灰常严重的问题啊：
所有的返回导航数据只要是被我收藏过以后，collect字段永远为true ，就算切换其他的账号，或者直接不传cookie 也是返回的true，就算做了取消收藏操作，也没效果
老大你可以看一下 https://www.wanandroid.com/navi/json 返回的数据,第一条和第二条collect字段都是为 true的，因为他们被我收藏了。。。

**Comment by hongyangAndroid** [comment]
嗯......了解了......这个导航因为每个人返回相同，当时是做了缓存的~
收藏状态也会一直被缓存，等我晚上再修复下



---原始邮件---
发件人: "hegaojian"<notifications@github.com&gt;
发送时间: 2019年8月28日(星期三) 上午9:26
收件人: "hongyangAndroid/wanandroid"<wanandroid@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"张鸿洋"<623565791@qq.com&gt;;
主题: Re: [hongyangAndroid/wanandroid] 导航返回的数据中collect 字段一直为false,就算收藏了这个id也是返回false (#150)



老大，刚测试了一下，有灰常严重的问题啊：
 所有的返回导航数据只要是被我收藏过以后，collect字段永远为true ，就算切换其他的账号，或者直接不传cookie 也是返回的true，就算做了取消收藏操作，也没效果
 老大你可以看一下 https://www.wanandroid.com/navi/json 返回的数据,第一条和第二条collect字段都是为 true的，因为他们被我收藏了。。。

**Comment by hegaojian** [comment]
大佬，辛苦了，给大佬递茶

**Comment by hongyangAndroid** [comment]
在测试一哈，已经修复

**Comment by hegaojian** [comment]
亲测没问题了，谢谢大佬
