### ISSUE TITLE
登陆后积分相关UI未刷新

### ISSUE THREAD

**Issue by yanzhenjie** [hongyangAndroid/wanandroid#156]
在首页用户未登录状态下，登陆后积分模块未刷新，图示如下：
![image](https://user-images.githubusercontent.com/13534988/63820044-5a519580-c97a-11e9-8949-01b72bbe49b8.png)

**Comment by hongyangAndroid** [comment]
已修复

**Comment by yanzhenjie** [comment]
:relieved: 是不是要给我加10分哇？我的账号是：yanzhenjie
