### ISSUE TITLE
收藏问题（网页）

### ISSUE THREAD

**Issue by 1527115168** [hongyangAndroid/wanandroid#157]
1.在主页列表点击一个未收藏的item进去详情界面（如玩 Android 更新了两个功能）
2.详情界面点击收藏--成功
3.列表界面页点击收藏--成功
4.列表界面页点击取消收藏--成功（此时状态是取消的）
5.刷新列表界面，发现还是收藏的状态

**Comment by hongyangAndroid** [comment]
感谢反馈，已经修复~
