### ISSUE TITLE
卑微滴提个需求：积分接口中可以增加一个自己当前排名的字段莫？

### ISSUE THREAD

**Issue by hegaojian** [hongyangAndroid/wanandroid#159]
积分功能个人感觉推出的很nice，很大地提高了大家的积极竞争性与活跃度，害的我每天心心念打开玩安卓，先看看自己的排名上升了没，然后再刷刷有没有什么新文章，我都已经栽在这里面出不去了

**Comment by hongyangAndroid** [comment]
感谢支持呀，这周末就做，上线通知你

**Comment by hegaojian** [comment]
谢谢大佬采纳，希望玩安卓越来越完善，越做越好

**Comment by hongyangAndroid** [comment]
![image](https://user-images.githubusercontent.com/10704521/64059868-d48e4e00-cbf6-11e9-9b56-b971d8826b2f.png)

json 接口：

```
https://www.wanandroid.com/lg/coin/userinfo/json
```

需要登录后访问。

**Comment by hegaojian** [comment]
完美 !
