### ISSUE TITLE
开放网站API

### ISSUE THREAD

**Issue by perqin** [hongyangAndroid/wanandroid#16]
希望网站稳定后能开放API，方便开发第三方客户端。这个建议在其他issue有提到，我在这里单独开一个，鸿神有相关进展可以直接在这里更新，关心的小伙伴也可以直接subscribe。 XD

**Comment by hongyangAndroid** [comment]
感谢~~这个一定高优开发~

**Comment by chuwe1** [comment]
顶

**Comment by hongyangAndroid** [comment]
[API](http://www.wanandroid.com/blog/show/2)

[示例代码](http://www.wanandroid.com/blog/show/2029)

**Comment by harry235day** [comment]
大佬 http://www.wanandroid.com/article/list/1/json接口的问题
jquery ajax 跨域访问 会出现 Uncaught SyntaxError: Unexpected token :

**Comment by hongyangAndroid** [comment]
@harry235day 这边只能保证这个地址可以正常访问，跨域问题需要自行解决。
