### ISSUE TITLE
积分获取历史返回数据建议

### ISSUE THREAD

**Issue by hegaojian** [hongyangAndroid/wanandroid#160]
"coinCount": 32,
            "date": 1567267379000,
            "desc": "2019-09-01 00:02:59 签到,积分：10 + 22",
            "id": 35494,
            "type": 1,
            "userId": 27535,
            "userName": "xxxxxxxxxx"

目前返回的数据格式是这样子的，建议修改：
desc字段不要拼接时间了，目前写在界面上时间+说明一行会很长且会比较丑，如果我去截取，按照签到 去掉前面一部分时间的话，我怕会出问题，万一以后获取的desc不是签到类型岂不痛哉，反正你已经给了date字段了，我们如果需要拼接的话可以自己加

**Comment by hongyangAndroid** [comment]
哈哈，那个是我自己用来看的，可以自己拼接的，type=1为登录给的积分，日期，数量都有。

**Comment by hegaojian** [comment]
那type = 2的时候呢，我这边没有这个类型的数据，木得参考哦~~~~

**Comment by hegaojian** [comment]
![2345截图20190901131026](https://user-images.githubusercontent.com/18655288/64072025-f00e5d00-ccb9-11e9-97a6-cca2c608f464.jpg)
![2345截图20190901131150](https://user-images.githubusercontent.com/18655288/64072031-21872880-ccba-11e9-9438-8745c7067775.jpg)
鸿大，现在目前的话有这些类型， 如果我们自己去拼接的话，会比较死板了，不够灵活，如果以后出现了一个新的类型，可能会出问题，感觉还是鸿大你这边修改下的desc好点呢
比如说值为   每日签到一积分：10+22 又或者直接给 报备严重bug

**Comment by hongyangAndroid** [comment]
嗯，那我稍后加个字段吧，当前这个字段历史数据太多了，数据没法清理了。

**Comment by hegaojian** [comment]
嗯嗯，好的

**Comment by hongyangAndroid** [comment]
![image](https://user-images.githubusercontent.com/10704521/64078922-68edd300-cd13-11e9-8825-6e511a7f1bc1.png)
添加了 reason 字段。

**Comment by hegaojian** [comment]
收到，谢谢大佬
