### ISSUE TITLE
获取个人积分接口的数据是否可以考虑就合并到登录接口里面？

### ISSUE THREAD

**Issue by lx36301766** [hongyangAndroid/wanandroid#162]
如题，每次登录成功都还要去额外调用一次获取积分的接口，积分这个数据也不会存在需要单独刷新的场景吧，应该都是跟随登录接口一起调用的，既然这样还不如就把数据放一起

**Comment by hongyangAndroid** [comment]
不行呀，后续会有很多加分的case，登录只是一种类型。
