### ISSUE TITLE
app开启就崩溃了

### ISSUE THREAD

**Issue by gaowch** [hongyangAndroid/wanandroid#164]
我是在官网右侧联系我们下面的下载地址下的app

**Comment by BeyondWorlds** [comment]
我也遇到了，酷安扫码下载的

**Comment by goweii** [comment]
感谢反馈，晚上回去修复！

**Comment by goweii** [comment]
留下手机型号和android版本吧，我好排查，感谢！

**Comment by gaowch** [comment]
> 留下手机型号和android版本吧，我好排查，感谢！

华为荣耀8，android8.0

**Comment by BeyondWorlds** [comment]
华为P9Plus  8.0.0,

**Comment by goweii** [comment]
已发更新，因为手头没有8.0机型不知道修复了没😂，希望更新后能再反馈下

**Comment by gaowch** [comment]
手机扫码下载ok，可以正常进入了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Goweii"<notifications@github.com&gt;; 
发送时间: 2019年9月5日(星期四) 上午8:30
收件人: "hongyangAndroid/wanandroid"<wanandroid@noreply.github.com&gt;; 
抄送: "-查无此人。"<844376241@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [hongyangAndroid/wanandroid] app开启就崩溃了 (#164)




已发更新，因为手头没有8.0机型不知道修复了没😂，希望更新后能再反馈下
 
&mdash;
