### ISSUE TITLE
我想使用vue开发一个H5版wanandroid

### ISSUE THREAD

**Issue by shiwobuhaoma** [hongyangAndroid/wanandroid#165]
可否解决一下后台开放接口的跨域问题？

**Comment by hongyangAndroid** [comment]
跨域问题，是要我怎么解决呀，搞一些 jsonp 的接口？

**Comment by shiwobuhaoma** [comment]
谢谢您的回复！

如果后台是springboot开发，可以在类或者方法上加注解@CrossOrigin，要求jdk1.8

**Comment by hongyangAndroid** [comment]
噢噢 不是呢~~ 不过倒是有一些 Vue的开源项目，可以参考下。
