### ISSUE TITLE
鸿神，分享项目，项目描述有啥要注意的吗？

### ISSUE THREAD

**Issue by hegaojian** [hongyangAndroid/wanandroid#166]
我想分享一个github项目，项目描述是直接填我GItHub中README的内容，还是要自己重新排版自己编写的？

**Comment by hongyangAndroid** [comment]
描述一般就是简单一句话，用于标题下面显示的，会自动抓取readme生成页面。

**Comment by hegaojian** [comment]
好的，鸿神，我提交啦，帮忙审核下哦
