### ISSUE TITLE
积分排行榜接口发现了一个问题

### ISSUE THREAD

**Issue by iceCola7** [hongyangAndroid/wanandroid#167]
https://www.wanandroid.com/coin/rank/1/json

接口中返回数据中 rank 字段和 userId 字段一直返回0

![image](https://user-images.githubusercontent.com/20675928/64330402-79e46000-d003-11e9-8002-1d8315f8839d.png)

**Comment by hongyangAndroid** [comment]
这两个字段别用哈，序号其实就是排名。我给别的接口加的字段，忘了屏蔽了

**Comment by iceCola7** [comment]
哦哦好的

**Comment by hongyangAndroid** [comment]
已经修复上线,rank 为排名，新增字段 level 为用户当前等级。

个人积分接口，https://www.wanandroid.com/lg/coin/userinfo/json ，也新增了等级Level 字段。
