### ISSUE TITLE
需要登录的相关API ResponseHeader中的Content-Type?

### ISSUE THREAD

**Issue by phoenixsky** [hongyangAndroid/wanandroid#174]
比如收藏列表的接口在`ResponseHeader`中`Content-Type`的值
![image](https://user-images.githubusercontent.com/6359214/64931823-98e9ba00-d86d-11e9-9017-a24cfb3879eb.png)

是否可以修改为类似其他接口的`application/json;charset=UTF-8`,
因为有些网络库在解析response时,会根据这个`Content-Type`来进行响应的解析.

而实际上未登录的时候,返回值也是json格式
```json
{"errorCode":-1001,"errorMsg":"请先登录！"}
```

**Comment by hongyangAndroid** [comment]
已修复，欢迎测试。

**Comment by phoenixsky** [comment]
是不是可以给我加个10积分。账号为funandroid 哈哈哈

**Comment by hongyangAndroid** [comment]
已加~

**Comment by phoenixsky** [comment]
这....
![image](https://user-images.githubusercontent.com/6359214/65208587-1f99d380-dac8-11e9-8c2e-9311fd2923f0.png)
签到的加成没有了.....
而且签到不是10分么,怎么成11了.以后每天我的基数是不是都比他们多一分.长此以往.哈哈哈
告不告诉你呢

**Comment by hongyangAndroid** [comment]
哈哈，10+29是基数为10的最大值，转向11+0啦。

**Comment by phoenixsky** [comment]
额,这样 哈哈...我还窃喜一下.
