### ISSUE TITLE
本站积分规则页面显示问题

### ISSUE THREAD

**Issue by LaoXiZi** [hongyangAndroid/wanandroid#175]
360安全浏览器极速模式下，收藏栏为显示状态出现的。

![2019-09-16_192135](https://user-images.githubusercontent.com/23638133/64954306-c5c2bf00-d8b7-11e9-9162-29305495b502.png)
![2019-09-16_192315](https://user-images.githubusercontent.com/23638133/64954307-c65b5580-d8b7-11e9-932a-767400f93603.png)

**Comment by hongyangAndroid** [comment]
已经修复，求测试

**Comment by LaoXiZi** [comment]
测试通过，显示正常ヾ(◍°∇°◍)ﾉﾞ
