### ISSUE TITLE
积分获取异常

### ISSUE THREAD

**Issue by Kbaseczy** [hongyangAndroid/wanandroid#176]
我在玩安卓app登录后，积分记录显示11+0，当我在网站上登录后依然是11+0。
![积分获取Bug](https://user-images.githubusercontent.com/40874618/65096634-3670f500-d9f8-11e9-9796-1e755515b0ff.jpg)
用户账号：15541125277

**Comment by hongyangAndroid** [comment]
是这样的规则，基数变化就从0开始啦。

**Comment by Kbaseczy** [comment]
> 是这样的规则，基数变化就从0开始啦。

What a shame!
