### ISSUE TITLE
代办清单一个bug：大于号小于号会乱码

### ISSUE THREAD

**Issue by lanshifu** [hongyangAndroid/wanandroid#181]
https://www.wanandroid.com/lg/todo/list/0
mac打开->添加代办清单->输入标题和详情

效果看下面截图。

下班前习惯在上面保存一些文字，然后回家打开发现带有<> 号的都会被转成 \&lt;和\&gt;，影响体验。

user：lanshifu

**Comment by lanshifu** [comment]
![image](https://user-images.githubusercontent.com/20284668/65369657-70552c00-dc82-11e9-9c7a-afc42925644d.png)

**Comment by lanshifu** [comment]
要看截图彩信，这是添加之前的内容，另一张截图是保存后再次打开的内容，大于号等于号应该是被转成另一种编码了，github能正确识别出来。
![image](https://user-images.githubusercontent.com/20284668/65369695-02f5cb00-dc83-11e9-9a9f-39cf86ece090.png)

**Comment by hongyangAndroid** [comment]
嗯嗯 我看一下能否修复 有可能是防止xss导致。

**Comment by hongyangAndroid** [comment]
已修复。
