### ISSUE TITLE
开放体系中的 广场Tab查询返回的数据有问题

### ISSUE THREAD

**Issue by hegaojian** [hongyangAndroid/wanandroid#182]
具体APi：https://www.wanandroid.com/article/list/0/json?cid=494
发现author字段为空，但新加了一个字段shareUser却有值
因为以前都是取值author字段来显示的，现在导致很多app端显示的作者都是空的了，建议广场tab的数据把author也赋上值

**Comment by hongyangAndroid** [comment]
网站上也有这个问题...

正在兼容处理中。

目前网站显示逻辑：

author 不为空，显示作者。
author 为空，shareUser 不为空，显示分享人。

两者都没有，则不显示相关信息。

至于 json 返回数据，我一会加一个拦截器，把 author 为 null 的设置为 shareUser，但是还是建议客户端能做下判断。

**Comment by hegaojian** [comment]
好的，no 爬波冷，thanks for red god

**Comment by hongyangAndroid** [comment]
check 了一遍...因为网站也用了 open api，没法区分出来...

不能设置分享者->作者，因为

作者的落地页
https://www.wanandroid.com/article/list/0?author=%E9%B8%BF%E6%B4%8B

分享者落地页
https://www.wanandroid.com/user/1871/articles/1

不同。

稍后我更新下公告和 OPEN API注意事项。

**Comment by hegaojian** [comment]
嗯嗯，好的，我去把自己的App端逻辑也修改下  :blush:

**Comment by hegaojian** [comment]
这算不算bug啊，阔以加点积分不 :heart_eyes:

**Comment by hongyangAndroid** [comment]
需要提供一下用户名~~~

**Comment by hegaojian** [comment]
17508491840  :smile: 谢谢

**Comment by hongyangAndroid** [comment]
done，我该谢谢你的反馈~

**Comment by hegaojian** [comment]
哈哈，我也是今天刷App的时候偶然发现的，看到体系中最下面有个广场，就点进去瞅了一眼，然后就发现界面不对头了...
emmm,我感觉我设计编写的玩安卓App很用心了，鸿神你看看怎么样https://github.com/hegaojian/WanAndroid

请鸿神给我一个来自____的肯定 :laughing:
### A.黑铁    B.青铜     C. 黄金     D.钻石

**Comment by hongyangAndroid** [comment]
D

**Comment by hegaojian** [comment]
谢谢鸿神，刚刚修改代码的时候又发现了新的bug
1.收藏体系-广场下的文章后，在收藏文章列表中返回的 author字段为空，且没有返回shareUser字段
2.收藏体系-广场下的文章，在收藏文章列表中发现的数据中，chapterName字段会出现很多是空的情况
示例的数据： 目前的第一条数据抛物线教你学携程... 收藏后，收藏列表中chapterName字段数据为空
第三条：基于腾讯X5开源库，提高webview开发效率.... 收藏列表中chapterName字段数据为 广场

**Comment by hongyangAndroid** [comment]
现在chaptername还是空的吗？我晚上的时候改了。

 作者这个信息是真没了~收藏的文章目前没有分享人字段~

**Comment by hegaojian** [comment]
chaptername 字段现在有值了，但是 author 字段还是空

**Comment by hongyangAndroid** [comment]
嗯，author目前确实没有，我思考下有没有必要加进去~

**Comment by hegaojian** [comment]
非常有必要啊，怎么能没有作者呢，按理来说其他的类型都有作者，不能因为是广场的原因就没有啊 :joy:

**Comment by hegaojian** [comment]
老大，你看我的界面都不对头了 :weary:
![Screenshot_2019-09-21-23-02-40-908_me hegj wandro](https://user-images.githubusercontent.com/18655288/65375188-2e99a500-dcc5-11e9-893b-059ddf23ac5a.jpg)

**Comment by hegaojian** [comment]
![Screenshot_2019-09-21-23-02-40-908_me hegj wandro](https://user-images.githubusercontent.com/18655288/65375196-58eb6280-dcc5-11e9-8fab-5ca8afbf54c3.jpg)
