### ISSUE TITLE
收藏接口没有添加 shareUser 等字段吗

### ISSUE THREAD

**Issue by iceCola7** [hongyangAndroid/wanandroid#190]
鸿神，能否在收藏接口添加 shareUser 字段啊，在APP收藏页展示作者的位置为空了~~
接口： https://www.wanandroid.com/lg/collect/list/0/json

![image](https://user-images.githubusercontent.com/20675928/66728710-2f16fd00-ee79-11e9-9d24-4c39c719d5bb.png)

**Comment by lx36301766** [comment]
同上

**Comment by phoenixsky** [comment]
我的页面直接NPE了😢

**Comment by hongyangAndroid** [comment]
因为收藏支持直接写标题和链接，一定会有没有user的情况~~

**Comment by hongyangAndroid** [comment]
所有收藏如果真要加作者，就会出现：

1. 站内文章：有author字段；
2. 分享文章：有shareUser字段；
3. 直接自己添加的，是没有任何字段的。

不知道大家有啥意见。

**Comment by iceCola7** [comment]
既然是这样，还是不要加了吧~，因为还是有可能有的没有任何字段，还是改改收藏界面，处理下别出问题了比较好~  哈哈哈 ^_^

**Comment by hongyangAndroid** [comment]
那就暂时不加啦~~

个人收藏其实只能自见，也不想搞得太复杂~
