### ISSUE TITLE
提交文章报错

### ISSUE THREAD

**Issue by FishInWater-1999** [hongyangAndroid/wanandroid#191]
Tomcat 提示 JDBC 出错：
--------------------------------------
HTTP Status 500 - Request processing failed; nested exception is org.springframework.jdbc.UncategorizedSQLException: Hibernate operation: could not insert: [com.zhy.xueandroid.bean.Article]; uncategorized SQLException for SQL [insert into tb_article (apk_link, _audit, author, chapter_id, chapter_name, course_id, _desc, envelope_pic, link, origin, project_link, publish_time, self_visible, share_date, share_user, title, type, user_id, visible, zan) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; SQL state [HY000]; error code [1366]; Incorrect string value: '\xF0\x9F\x94\xA5 \xE9...' for column 'title' at row 1; nested exception is java.sql.SQLException: Incorrect string value: '\xF0\x9F\x94\xA5 \xE9...' for column 'title' at row 1
------------------------------------------------------------------------

具体信息
---------------------------------------------------------------
exception

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.jdbc.UncategorizedSQLException: Hibernate operation: could not insert: [com.zhy.xueandroid.bean.Article]; uncategorized SQLException for SQL [insert into tb_article (apk_link, _audit, author, chapter_id, chapter_name, course_id, _desc, envelope_pic, link, origin, project_link, publish_time, self_visible, share_date, share_user, title, type, user_id, visible, zan) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; SQL state [HY000]; error code [1366]; Incorrect string value: '\xF0\x9F\x94\xA5 \xE9...' for column 'title' at row 1; nested exception is java.sql.SQLException: Incorrect string value: '\xF0\x9F\x94\xA5 \xE9...' for column 'title' at row 1
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:894)
	org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:789)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	com.zhy.xueandroid.web.xss.XssFilter.doFilter(XssFilter.java:33)
	com.zhy.xueandroid.web.SystemContextFilter.doFilter(SystemContextFilter.java:23)
	org.springframework.orm.hibernate3.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:198)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
root cause

org.springframework.jdbc.UncategorizedSQLException: Hibernate operation: could not insert: [com.zhy.xueandroid.bean.Article]; uncategorized SQLException for SQL [insert into tb_article (apk_link, _audit, author, chapter_id, chapter_name, course_id, _desc, envelope_pic, link, origin, project_link, publish_time, self_visible, share_date, share_user, title, type, user_id, visible, zan) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; SQL state [HY000]; error code [1366]; Incorrect string value: '\xF0\x9F\x94\xA5 \xE9...' for column 'title' at row 1; nested exception is java.sql.SQLException: Incorrect string value: '\xF0\x9F\x94\xA5 \xE9...' for column 'title' at row 1
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:83)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
	org.springframework.orm.hibernate3.HibernateAccessor.convertJdbcAccessException(HibernateAccessor.java:424)
	org.springframework.orm.hibernate3.HibernateAccessor.convertHibernateAccessException(HibernateAccessor.java:410)
	org.springframework.orm.hibernate3.HibernateTemplate.doExecute(HibernateTemplate.java:411)
	org.springframework.orm.hibernate3.HibernateTemplate.executeWithNativeSession(HibernateTemplate.java:374)
	org.springframework.orm.hibernate3.HibernateTemplate.save(HibernateTemplate.java:683)
	com.zhy.xueandroid.dao.ArtilceDao.add(ArtilceDao.java:109)
	com.zhy.xueandroid.service.ArticleService.addUserArticleForUser(ArticleService.java:319)
	sun.reflect.GeneratedMethodAccessor2024.invoke(Unknown Source)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:606)
	org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)

root cause

java.sql.SQLException: Incorrect string value: '\xF0\x9F\x94\xA5 \xE9...' for column 'title' at row 1
	com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1074)
	com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4120)
	com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4052)
	com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2503)
	com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2664)
	com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2794)
	com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
	com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2458)
	com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2375)
	com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2359)
	org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:102)
	org.hibernate.id.IdentityGenerator$GetGeneratedKeysDelegate.executeAndExtract(IdentityGenerator.java:94)
	org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:57)

**Comment by FishInWater-1999** [comment]
出错原因是

分享文章的 文章标题不能含有 🔥等特殊字符

**Comment by hongyangAndroid** [comment]
嗯嗯，我晚点修复下，主要是不兼容emoji

**Comment by hongyangAndroid** [comment]
已修复~
