### ISSUE TITLE
积分排行榜 rank全部返回0

### ISSUE THREAD

**Issue by ithomasoft** [hongyangAndroid/wanandroid#194]
https://www.wanandroid.com/coin/rank/1/json

**Comment by ithomasoft** [comment]
{"data":{"curPage":1,"datas":[{"coinCount":2334,"rank":0,"userId":20382,"username":"g**eii"},{"coinCount":2277,"rank":0,"userId":27535,"username":"1**08491840"},{"coinCount":2014,"rank":0,"userId":2,"username":"x**oyang"},{"coinCount":1924,"rank":0,"userId":833,"username":"w**lwaywang6"},{"coinCount":1904,"rank":0,"userId":3559,"username":"A**ilEyon"},{"coinCount":1837,"rank":0,"userId":9621,"username":"S**24n"},{"coinCount":1819,"rank":0,"userId":1534,"username":"j**gbin"},{"coinCount":1789,"rank":0,"userId":863,"username":"m**qitian"},{"coinCount":1770,"rank":0,"userId":22832,"username":"7**502274@qq.com"},{"coinCount":1719,"rank":0,"userId":7809,"username":"1**23822235"},{"coinCount":1715,"rank":0,"userId":15603,"username":"r**eryxx"},{"coinCount":1710,"rank":0,"userId":27602,"username":"l**hehan"},{"coinCount":1710,"rank":0,"userId":2068,"username":"i**Cola"},{"coinCount":1710,"rank":0,"userId":1440,"username":"w**.wanandroid.com"},{"coinCount":1709,"rank":0,"userId":3710,"username":"r**one"},{"coinCount":1697,"rank":0,"userId":7590,"username":"陈**啦啦啦"},{"coinCount":1697,"rank":0,"userId":23244,"username":"a**ian"},{"coinCount":1686,"rank":0,"userId":7541,"username":"l**64301766"},{"coinCount":1675,"rank":0,"userId":1871,"username":"l**shifu"},{"coinCount":1654,"rank":0,"userId":3753,"username":"S**phenCurry"},{"coinCount":1644,"rank":0,"userId":10010,"username":"c**01220122"},{"coinCount":1644,"rank":0,"userId":27596,"username":"1**5915093@qq.com"},{"coinCount":1644,"rank":0,"userId":8152,"username":"t**g111"},{"coinCount":1644,"rank":0,"userId":2199,"username":"M**459"},{"coinCount":1626,"rank":0,"userId":24177,"username":"l**大白菜"},{"coinCount":1624,"rank":0,"userId":6142,"username":"c**huah"},{"coinCount":1624,"rank":0,"userId":28607,"username":"S**Brother"},{"coinCount":1605,"rank":0,"userId":7710,"username":"i**Cola7"},{"coinCount":1587,"rank":0,"userId":14829,"username":"l**changwen"},{"coinCount":1585,"rank":0,"userId":2073,"username":"s**joeson"}],"offset":0,"over":false,"pageCount":208,"size":30,"total":6239},"errorCode":0,"errorMsg":""}

**Comment by iceCola7** [comment]
https://github.com/hongyangAndroid/wanandroid/issues/167

**Comment by hongyangAndroid** [comment]
这周末修复~

**Comment by hongyangAndroid** [comment]
已经修复上线,rank 为排名，新增字段 level 为用户当前等级。

个人积分接口，https://www.wanandroid.com/lg/coin/userinfo/json ，也新增了等级Level 字段。
