### ISSUE TITLE
我在网页里链接打开接口没问题 但是 在app中报错

### ISSUE THREAD

**Issue by Mstian** [hongyangAndroid/wanandroid#198]
{
	"errMsg": "request:fail abort"
}

在提交issue过程中 有好了，时好时坏感觉

**Comment by hongyangAndroid** [comment]
哪个接口？

**Comment by hongyangAndroid** [comment]
至少需要贴一下访问接口详细的 url，访问方式，详细的日志~

**Comment by Mstian** [comment]
我目前只用了首页列表和 首页轮播图接口

**Comment by Mstian** [comment]
https://www.wanandroid.com/article/list/1/json
https://www.wanandroid.com/banner/json
访问方式 都是在按照 文档上的 能访问到 有时候 会报错 
{
"errMsg": "request:fail abort"
}

**Comment by hongyangAndroid** [comment]
首页接口 网站用的 和开放 API 相同的接口，稳定性应该有保证的。

从request:fail abort，感觉和网络有关，或者 https相关。

**Comment by Mstian** [comment]
ok 好的 我baseurl 全是 https呢 我自己再查查 谢谢大哥
