### ISSUE TITLE
bug list 

### ISSUE THREAD

**Issue by hongyangAndroid** [hongyangAndroid/wanandroid#2]
1. 点击bejson这个的时候，其他的字号会变小

**Comment by WuMaoQiang** [comment]
知识体系 一级分类里的选项点击后有明显的左右移动现象。比如点击开发环境，再点基础知识，会有明显的左右移动

**Comment by hongyangAndroid** [comment]
恩恩，bug。

**Comment by hongyangAndroid** [comment]
bug 1 fixed;
知识体系那个，详细查了一下，原因是：
点击基础知识时，页面存在滚动条；点击四大组件时滚动条消失；导致显示内容区域宽度变化，所以造成分类数据折行一个。
