### ISSUE TITLE
建议增加小功能

### ISSUE THREAD

**Issue by xue1301117865** [hongyangAndroid/wanandroid#20]
建议增加一个RGB颜色与16进制颜色值的互相转换,现使用的在现在工具http://www.sioe.cn/yingyong/yanse-rgb-16/

**Comment by hongyangAndroid** [comment]
![image](https://user-images.githubusercontent.com/10704521/33180222-f22b1b34-d0a6-11e7-803e-3fb46ee1b94f.png)
[wanandroid取色器](http://www.wanandroid.com/tools/color)

这个取色器支持RGB到16进制的转化，更新了一个底部包含一个百分比到16进制的转化表，一般用于透明度。
