### ISSUE TITLE
注册接口好像有问题，我在postman里面请求 没问题，但是 在项目里 发请求 报错 内容如下

### ISSUE THREAD

**Issue by Mstian** [hongyangAndroid/wanandroid#200]
报错内容：The request sent by the client was syntactically incorrect

https://www.wanandroid.com/user/register

方法：POST
参数
	username,password,repassword
         qwer        123456     123456 

<html><head><title>Apache Tomcat/7.0.77 - Error report</title><style></style> </head><body><h1>HTTP Status 400 - </h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>The request sent by the client was syntactically incorrect.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.77</h3></body></html> at common\ajax.js:16
22:50:17.566 <html><head><title>Apache Tomcat/7.0.77 - Error report</title><style></style> </head><body><h1>HTTP Status 400 - </h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>The request sent by the client was syntactically incorrect.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.77</h3></body></html>

**Comment by hongyangAndroid** [comment]
400，语法错误，一般不是服务器问题。

PS：postman 如果能成功，一般后端接口没有问题。
