### ISSUE TITLE
洋神，反馈个小问题

### ISSUE THREAD

**Issue by kukyxs** [hongyangAndroid/wanandroid#202]
`https://www.wanandroid.com/user/5325/share_articles/1/json` 这个接口返回没有数据，查询分享文章用户的接口

**Comment by kukyxs** [comment]
看了下，通过网页版打开可以查询到

**Comment by hegaojian** [comment]
+1 ，在移动端上，大部分查询是没问题的，但是查询部分用户就会失败

**Comment by hongyangAndroid** [comment]
没发现呀，晚上我详细看下，给各位回复。

**Comment by hongyangAndroid** [comment]
已经复现问题，没考虑到一些用户没有积分，导致后台 NPE 了。

所以 json 接口返回了 -1 ；

网页兼容性比较强，只是相关数据未显示。

给没有积分相关的用户，设置了默认 0 积分，今晚上线。

感谢反馈~
