### ISSUE TITLE
广场列表接口返回的数据个数从第二页开始是19个

### ISSUE THREAD

**Issue by iceCola7** [hongyangAndroid/wanandroid#205]
鸿洋，广场列表接口返回的数据个数有个小问题
接口：https://www.wanandroid.com/user_article/list/1/json
如下图，size是20，但是从第二页开始实际上只有19个

![image](https://user-images.githubusercontent.com/20675928/69004014-e86c6500-0946-11ea-94ae-67ee39ab1aad.png)

^_^ 用户名：iceCola7

**Comment by hongyangAndroid** [comment]
因为有自见的文章，这部分只有作者本人能看到，非ben'ren本人被过滤掉了，不过这方面文章非常少。

![image](https://user-images.githubusercontent.com/10704521/69900072-5afb2d00-13aa-11ea-981a-219a706ebd87.png)
