### ISSUE TITLE
为什么我得应用老是要打开拼多多

### ISSUE THREAD

**Issue by mm46468648** [hongyangAndroid/wanandroid#206]
当我的应用处于后台或者前台,每隔一段时间当我解锁的时候总是弹出,是否允许我得应用打开平多多或者淘宝,我检查了我的代码,并没有请求跳转他们的包名,不知道为什么会这样,这样对用户的体验很不好.怀疑是我们接入广告sdk的问题.但是不知道怎么排查,请求大佬帮忙解决,

**Comment by hongyangAndroid** [comment]
应该是简书的落地页跳转的把，可以在 webview 里面拦截下 url。

我已经在 open api 里面标明了：

很多 H5 页面会恶意跳转淘宝等，可以在 webview 的 shouldOverrideUrlLoading 中做一下拦截，非常影响用户体验。
