### ISSUE TITLE
搜索接口 具体怎么写？？？

### ISSUE THREAD

**Issue by Mstian** [hongyangAndroid/wanandroid#207]
https://www.wanandroid.com/article/query/0/json

方法：POST
参数：
	页码：拼接在链接上，从0开始。
	k ： 搜索关键词

我写成https://www.wanandroid.com/article/query/0/json?k="安卓"

请求不到 具体要咋写呢？

**Comment by hongyangAndroid** [comment]
POST 接口呀。

POST 的参数你怎么能拼接在 url 上呢。

可以先百度搜索学习下 GET，POST 请求区别，然后再学习下 postman 的使用，最后拿 postman 测试即可。
