### ISSUE TITLE
注册失败

### ISSUE THREAD

**Issue by CB2Git** [hongyangAndroid/wanandroid#21]
提示信息：
Validation failed for classes [com.zhy.xueandroid.bean.User] during persist time for groups [javax.validation.groups.Default, ] List of constraint violations:[ ConstraintViolationImpl{interpolatedMessage='用户Id不合法', propertyPath=id, rootBeanClass=class com.zhy.xueandroid.bean.User, messageTemplate='用户Id不合法'} ]
注册用户名:123456789
密码:8位数的纯数字

**Comment by hongyangAndroid** [comment]
非常感谢反馈，已经修复，现在可以正常注册了。

原因：昨晚上线新功能的时候，做了一个通用性判断，判断了用户的Id，忽略了注册时用户无Id.

您可以尝试下后反馈。

**Comment by CB2Git** [comment]
麻烦了，已经注册成功。另外hongyang大大能不能将用户名字符数缩减一点，6个有点长了~

**Comment by hongyangAndroid** [comment]
噢噢，下个版本改成4位，等这边用户个人信息、以及修改页做好。
