### ISSUE TITLE
站内文章和站外文章区别在哪里呢

### ISSUE THREAD

**Issue by mosquitoxiang** [hongyangAndroid/wanandroid#211]

**Comment by hongyangAndroid** [comment]
站内文章：

首页看到的那些文章，可以点击"收藏按钮"收藏的都是，一般只需要 id 即可。

站外文章：

指的是你个人手动输入的标题和链接，收藏的文章，这种没有 id，需要手动填写标题和链接。

**Comment by mosquitoxiang** [comment]
> 站内文章：
> 
> 首页看到的那些文章，可以点击"收藏按钮"收藏的都是，一般只需要 id 即可。
> 
> 站外文章：
> 
> 指的是你个人手动输入的标题和链接，收藏的文章，这种没有 id，需要手动填写标题和链接。

能不能给个玩安卓的交流群
