### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by JiangHaiYang01** [hongyangAndroid/wanandroid#214]
1576720671216,2019.12.19 09:57:51.216,INFO,log,http----> --> GET https://www.wanandroid.com/user/lg/private_articles/0/json
1576720671220,2019.12.19 09:57:51.220,INFO,log,http----> --> END GET
1576720671221,2019.12.19 09:57:51.221,INFO,log,http----> add heard [key]:Cookie [value]:[JSESSIONID=89EC89C5BEF7C28CB8144207F4EBBED2; Path=/; Secure; HttpOnly, token_pass_wanandroid_com=8d671b38bf413abafa4cf0c30663492f; Domain=wanandroid.com; Expires=Thu, 02-Jan-2020 14:31:09 GMT; Path=/, loginUserName_wanandroid_com=18856907654; Domain=wanandroid.com; Expires=Thu, 02-Jan-2020 14:31:09 GMT; Path=/, loginUserName=18856907654; Expires=Thu, 02-Jan-2020 14:31:09 GMT; Path=/, token_pass=8d671b38bf413abafa4cf0c30663492f; Expires=Thu, 02-Jan-2020 14:31:09 GMT; Path=/]
1576720672045,2019.12.19 09:57:52.045,INFO,log,http----> <-- 200 OK https://www.wanandroid.com/user/lg/private_articles/0/json (822ms)
1576720672048,2019.12.19 09:57:52.048,INFO,log,http----> Server: Apache-Coyote/1.1
1576720672053,2019.12.19 09:57:52.053,INFO,log,http----> Cache-Control: private
1576720672061,2019.12.19 09:57:52.061,INFO,log,http----> Expires: Thu, 01 Jan 1970 08:00:00 CST
1576720672062,2019.12.19 09:57:52.062,INFO,log,http----> Set-Cookie: JSESSIONID=10F608C9071668A381C8ACCF498BB679; Path=/; Secure; HttpOnly
1576720672063,2019.12.19 09:57:52.063,INFO,log,http----> Content-Type: application/json;charset=UTF-8
1576720672065,2019.12.19 09:57:52.065,INFO,log,http----> Transfer-Encoding: chunked
1576720672065,2019.12.19 09:57:52.065,INFO,log,http----> Date: Thu, 19 Dec 2019 01:57:54 GMT
1576720672068,2019.12.19 09:57:52.068,INFO,log,http---->
1576720672070,2019.12.19 09:57:52.070,INFO,log,http----> {"data":{"coinInfo":{"coinCount":371,"level":4,"rank":805,"userId":36886,"username":"1**56907654"},"shareArticles":{"curPage":1,"datas":[{"apkLink":"","audit":0,"author":"","chapterId":494,"chapterName":"广场","collect":false,"courseId":13,"desc":"","envelopePic":"","fresh":true,"id":11044,"link":"https://github.com/JiangHaiYang01/IOS_Dialog","niceDate":"17分钟前","niceShareDate":"17分钟前","origin":"","prefix":"","projectLink":"","publishTime":1576719636000,"selfVisible":0,"shareDate":1576719636000,"shareUser":"18856907654","superChapterId":494,"superChapterName":"广场Tab","tags":[],"title":"仿iOS_dialog","type":0,"userId":36886,"visible":0,"zan":0}],"offset":0,"over":true,"pageCount":1,"size":20,"total":1}},"errorCode":0,"errorMsg":""}
1576720672070,2019.12.19 09:57:52.070,INFO,log,http----> <-- END HTTP (758-byte body)

1576720679417,2019.12.19 09:57:59.417,INFO,log,http----> --> GET https://www.wanandroid.com/user/lg/private_articles/1/json
1576720679422,2019.12.19 09:57:59.422,INFO,log,http----> --> END GET
1576720679426,2019.12.19 09:57:59.426,INFO,log,http----> add heard [key]:Cookie [value]:[JSESSIONID=89EC89C5BEF7C28CB8144207F4EBBED2; Path=/; Secure; HttpOnly, token_pass_wanandroid_com=8d671b38bf413abafa4cf0c30663492f; Domain=wanandroid.com; Expires=Thu, 02-Jan-2020 14:31:09 GMT; Path=/, loginUserName_wanandroid_com=18856907654; Domain=wanandroid.com; Expires=Thu, 02-Jan-2020 14:31:09 GMT; Path=/, loginUserName=18856907654; Expires=Thu, 02-Jan-2020 14:31:09 GMT; Path=/, token_pass=8d671b38bf413abafa4cf0c30663492f; Expires=Thu, 02-Jan-2020 14:31:09 GMT; Path=/]
1576720680131,2019.12.19 09:58:00.131,INFO,log,http----> <-- 200 OK https://www.wanandroid.com/user/lg/private_articles/1/json (708ms)
1576720680140,2019.12.19 09:58:00.140,INFO,log,http----> Server: Apache-Coyote/1.1
1576720680144,2019.12.19 09:58:00.144,INFO,log,http----> Cache-Control: private
1576720680147,2019.12.19 09:58:00.147,INFO,log,http----> Expires: Thu, 01 Jan 1970 08:00:00 CST
1576720680149,2019.12.19 09:58:00.149,INFO,log,http----> Set-Cookie: JSESSIONID=4A13F68C5C51F51047567D140C2B289B; Path=/; Secure; HttpOnly
1576720680153,2019.12.19 09:58:00.153,INFO,log,http----> Content-Type: application/json;charset=UTF-8
1576720680156,2019.12.19 09:58:00.156,INFO,log,http----> Transfer-Encoding: chunked
1576720680158,2019.12.19 09:58:00.158,INFO,log,http----> Date: Thu, 19 Dec 2019 01:58:03 GMT
1576720680160,2019.12.19 09:58:00.160,INFO,log,http---->
1576720680162,2019.12.19 09:58:00.162,INFO,log,http----> {"data":{"coinInfo":{"coinCount":371,"level":4,"rank":805,"userId":36886,"username":"1**56907654"},"shareArticles":{"curPage":1,"datas":[{"apkLink":"","audit":0,"author":"","chapterId":494,"chapterName":"广场","collect":false,"courseId":13,"desc":"","envelopePic":"","fresh":true,"id":11044,"link":"https://github.com/JiangHaiYang01/IOS_Dialog","niceDate":"17分钟前","niceShareDate":"17分钟前","origin":"","prefix":"","projectLink":"","publishTime":1576719636000,"selfVisible":0,"shareDate":1576719636000,"shareUser":"18856907654","superChapterId":494,"superChapterName":"广场Tab","tags":[],"title":"仿iOS_dialog","type":0,"userId":36886,"visible":0,"zan":0}],"offset":0,"over":true,"pageCount":1,"size":20,"total":1}},"errorCode":0,"errorMsg":""}
1576720680163,2019.12.19 09:58:00.163,INFO,log,http----> <-- END HTTP (758-byte body)

pageIndex change  但是  返回的数据集合是相同的

**Comment by hongyangAndroid** [comment]
![image](https://user-images.githubusercontent.com/10704521/71481603-8520fd00-2839-11ea-880c-d6cb3390ce60.png)

查了一下，这个接口页码是从 1 开始的。
