### ISSUE TITLE
积分排行榜接口每页rank字段，都是从1开始的

### ISSUE THREAD

**Issue by ASCII13** [hongyangAndroid/wanandroid#215]
- <a href="https://www.wanandroid.com/coin/rank/1/json">积分排行榜第一页</a>
- <a href="https://www.wanandroid.com/coin/rank/2/json">积分排行榜第二页</a>

rank 字段每一页计数都从1开始，这样感觉在上拉加载的时候，处理排名展示上不太方便，而且也不合理。

**Comment by hongyangAndroid** [comment]
看样子确实是 bug，我来修复一下。

**Comment by hongyangAndroid** [comment]
已修复，欢迎尝试反馈。

**Comment by ASCII13** [comment]
洋神是真的响应迅速啊！
