### ISSUE TITLE
这个每日一问是缺了数据吗？

### ISSUE THREAD

**Issue by jhbxyz** [hongyangAndroid/wanandroid#216]
https://www.wanandroid.com/wenda/show/10892
标题：每日一问 | Activity 旋转啦，重新下载怪我咯？
日期：2019-12-20 00:08

**Comment by hongyangAndroid** [comment]
缺数据是什么意思？没明白~

**Comment by jhbxyz** [comment]
搞错了，尴尬！百忙之中，还耽误洋哥，太不好意思了
