### ISSUE TITLE
搜索出现大量重复数据

### ISSUE THREAD

**Issue by xzm1102207843** [hongyangAndroid/wanandroid#218]
进入项目tab，然后搜索，uniApp出现大量重复的数据，在pc网站搜索不会出现此现象，wanAndroid账号：xzm1102207843  
![95C03DB47151BAE1BF5E420F7C2B62F8](https://user-images.githubusercontent.com/16155051/71943122-7e5f9600-31fa-11ea-9767-aec7d253c583.jpg)

**Comment by hongyangAndroid** [comment]
这个应该是这个 App 的 bug，看样子是这个项目：

https://github.com/iceCola7/WanAndroid

需要在这个地址提 issue 哈，因为不是我开源。

我主要负责修复网站的问题。
