### ISSUE TITLE
服务端没有对用户注册信息进行校验

### ISSUE THREAD

**Issue by CB2Git** [hongyangAndroid/wanandroid#22]
如题，使用"非法的"用户信息注册，比如test~-1234567890等，直接使用注册接口会注册成功

**Comment by CB2Git** [comment]
获取用户收藏列表，不传递JSESSIONID，只传递loginUserName以及loginUserPassword即可获取到信息(密码保存在本地真的好么?)，可以弄的和取消收藏的接口类似，使用JSESSIONID来校验登录状态>.<，ps:hongyang大大看了好多你的博客了啊！！！！

**Comment by CB2Git** [comment]
个人收藏列表第二页，没有取消收藏的选项，而是收藏的图标，点击没有反应。
测试用户:test_-863751944 密码:test_-863751944

**Comment by hongyangAndroid** [comment]
非常感谢反馈~ 
1. 收藏功能bug，已经修复；
2. 对于账号脱敏的问题，之前是考虑希望触发到任何链接能保证自动登录，所以存储在cookie中；后面会考虑脱敏。

**Comment by hongyangAndroid** [comment]
账号自动登录，已经修改为token 机制，不再明文。
