### ISSUE TITLE
登录请求不成功，报错

### ISSUE THREAD

**Issue by strivecheng** [hongyangAndroid/wanandroid#221]
405 Method Not Allowed
![image](https://user-images.githubusercontent.com/20623884/72337488-9dc85880-36fd-11ea-833d-6381198943d8.png)

**Comment by hongyangAndroid** [comment]
登录请使用 post 请求。
![image](https://user-images.githubusercontent.com/10704521/72363847-7e96ee80-3730-11ea-88d4-99639ac05533.png)

**Comment by strivecheng** [comment]
> 登录请使用 post 请求。
> ![image](https://user-images.githubusercontent.com/10704521/72363847-7e96ee80-3730-11ea-88d4-99639ac05533.png)

用的就是post，我用您发的kotlin版的app去登录也是报同样的问题
<img width="904" alt="WX20200115-091906@2x" src="https://user-images.githubusercontent.com/20623884/72396587-21269000-3778-11ea-9e8b-a2d05c334fe9.png">

**Comment by strivecheng** [comment]
> 登录请使用 post 请求。
> ![image](https://user-images.githubusercontent.com/10704521/72363847-7e96ee80-3730-11ea-88d4-99639ac05533.png)

洋神，但是我用postman测试是成功的😂
