### ISSUE TITLE
按昵称搜索文章接口和网站数据不一致

### ISSUE THREAD

**Issue by lx36301766** [hongyangAndroid/wanandroid#222]
如下，直接对比这两个链接的结果吧

https://www.wanandroid.com/article/list/0/json?author=goweii

https://www.wanandroid.com/user/20382/articles/1

**Comment by hongyangAndroid** [comment]
嗯，这两个链接是不同的数据。

第一个链接是点击 作者:xxx。
第二个链接是点击  分享人: xxx。

也就是第一个链接是搜索作者文章列表。
第二个链接是查看某个网站用户分享的文章列表。

**Comment by lx36301766** [comment]
找到了。。。
https://www.wanandroid.com/user/2/share_articles/1/json
