### ISSUE TITLE
分享相关bug

### ISSUE THREAD

**Issue by sw950729** [hongyangAndroid/wanandroid#223]
分享文章之后，进行删除操作，然后再次分享相同内容，会提示该文章已经分享过了。{"data":null,"errorCode":-1,"errorMsg":"该文已经被分享过"}

**Comment by hongyangAndroid** [comment]
https://www.wanandroid.com/lg/user_article/add/json

这个接口吗？

我试了下，没有复现，删除后可以正常分享。
