### ISSUE TITLE
常用网址收藏完成后，若名称过长，无法修改和删除

### ISSUE THREAD

**Issue by j1406493495** [hongyangAndroid/wanandroid#23]
![image](https://user-images.githubusercontent.com/7507072/33591722-13a2039e-d9c2-11e7-8a5b-206ff7963e1d.png)

**Comment by hongyangAndroid** [comment]
今晚会修复这个问题。  
PS：如果着急，可以右键审查把这个内容改短，然后会展示出。

**Comment by hongyangAndroid** [comment]
已经修复。
