### ISSUE TITLE
广场分享文章时间错误导致的排序错误

### ISSUE THREAD

**Issue by v200123** [hongyangAndroid/wanandroid#232]
![image](https://user-images.githubusercontent.com/29189439/77999241-ee4a6c00-7364-11ea-82b1-530a5187fcfd.png)
这是目前显示出来这篇文章分享出来的时间，但其实这文章分享已经很久了，却显示为3月28日的了。
下面是在个人中心查询到的时间
![image](https://user-images.githubusercontent.com/29189439/77999388-2c479000-7365-11ea-9159-be445ee7b44c.png)

**Comment by hongyangAndroid** [comment]
噢噢，这个是有意设计的。

个人中心的是显示的分享时间。

对外的入口显示的最后修改时间。

原因是这样的：

1. 比如 3.1 号你分享了一篇文章 ；
2. 我可能会在 3.2 号去设置下章节；
3. 这样对外的时间就是 3.2，个人中心的时间就是3.1了。

**Comment by v200123** [comment]
我才看到回复的消息，现在已经了解了，虽然之前猜测可能是修改时间
