### ISSUE TITLE
首页发布的文章时间不准确

### ISSUE THREAD

**Issue by liujin009** [hongyangAndroid/wanandroid#238]
首页发布的文章时间不准确，没有及时更新发布的时间，几天前的文章发布显示刚刚发布，请更正

**Comment by hongyangAndroid** [comment]
这个时间指的是，在本站更新的时间，例如：更新了文章所属章节等。

和文章的实际发布时间，是对应不上的，因为大部分都是站外的，获取实际时间，成本太高了。
