### ISSUE TITLE
获取收藏列表的Response的link字段错误

### ISSUE THREAD

**Issue by NianyiYang** [hongyangAndroid/wanandroid#244]
如题，调用收藏列表接口
`/lg/collect/list/0/json`
返回的 `link` 字段是 `http://xxx` 实际上应该是 `https://xxx` 
![image](https://user-images.githubusercontent.com/9956661/81477247-53895b00-9249-11ea-9243-873f05d52a96.png)

**Comment by hongyangAndroid** [comment]
已修复。
