### ISSUE TITLE
关于动态加载插件apk的动态权限申请请教

### ISSUE THREAD

**Issue by liangchenxijin** [hongyangAndroid/wanandroid#249]
请教一下，关于动态加载中宿主apk可以申请动态权限，但是在插件apk中如何申请权限？我现在写的项目中想加动态加载插件apk，但是插件apk中是有其他权限，宿主APP调用的时候插件apk是空白的，并没有提示权限操作，但是插件apk运行到手机上是有动态权限的，请鸿洋大神指点一下技术路线，谢谢！

**Comment by hongyangAndroid** [comment]
插件用到的权限，都需要在宿主注册，另外不建议提与网站无关问题呀、

**Comment by liangchenxijin** [comment]
鸿洋大神：
1.因为插件是一个apk文件；
2.我再你的公众号、wanandroid中找了一圈提问的地方没找到，实在对不住啊，加入有提问的的地方发个链接，谢谢！
感谢鸿洋！！！
