### ISSUE TITLE
【新功能意见箱】提供了文章落地页的展示

### ISSUE THREAD

**Issue by hongyangAndroid** [hongyangAndroid/wanandroid#25]
可以点击：
  [http://www.wanandroid.com/blog/4](http://www.wanandroid.com/blog/4)
查看效果

**Comment by hongyangAndroid** [comment]
已记录问题：

1. 长文会有段时间排版错乱，严重体验问题
2. 左右留白稍微大点
3. 顶部标题上下间距需要大点
4. 文字需要强制设置一个好看的。（360下文字单薄）
5. 行间距稍微变大

**Comment by wangzailfm** [comment]
需不需要增加个文章目录？
![image](https://user-images.githubusercontent.com/7636220/34085777-108ff928-e3d0-11e7-8195-8223e728c386.png)

**Comment by hymanAndroid** [comment]
@wangzailfm 感谢已经添加目录~
