### ISSUE TITLE
同一个一级列表，知识体系列表的superid 与 知识体系的 id不一致

### ISSUE THREAD

**Issue by yangsanning** [hongyangAndroid/wanandroid#250]
> 接口 https://www.wanandroid.com/tree/json
![image](https://user-images.githubusercontent.com/20766133/84355406-225bcc00-abf5-11ea-99ef-069d9ce875da.png)

> 接口 https://www.wanandroid.com/article/list/0/json?cid=94
![image](https://user-images.githubusercontent.com/20766133/84355433-31427e80-abf5-11ea-9f0e-3bc2018c7c1d.png)

**Comment by hongyangAndroid** [comment]
详细排查了一下。

后者确实是错的，显示的是该父章节第一个子栏目的 id。

![image](https://user-images.githubusercontent.com/10704521/84590722-8ee00080-ae6b-11ea-8791-271a2316db49.png)

当时是因为，点击父章节的时候，可以跳转到 该父章节的第一个栏目 id 下的文章列表。

所以这么设置值了。

直接改动影响较大，所以添加了一个字段：

realSuperChapterId

作为实际的父 chapterId.

**Comment by yangsanning** [comment]
感谢！
