### ISSUE TITLE
文章链接失效应当删除

### ISSUE THREAD

**Issue by pgaofeng** [hongyangAndroid/wanandroid#251]
有些文章的链接已失效，点进去是个空的界面，体验非常不友好，建议增加一个读者反馈功能，这样当我们发现是个空链接的时候可以点个反馈，然后查证后删除文章。

**Comment by hongyangAndroid** [comment]
![image](https://user-images.githubusercontent.com/10704521/85916669-a369c300-b885-11ea-862f-931eac1af703.png)


已上线该功能，鼠标指向一篇文章时，会出现「链接错误」按钮，点击即可反馈。
