### ISSUE TITLE
无法分享文章，不论是否勾选推送到首页，始终提示分享失败，积分不足，账号存在33积分

### ISSUE THREAD

**Issue by loper7** [hongyangAndroid/wanandroid#256]
无法分享文章，不论是否勾选推送到首页，始终提示分享失败，积分不足，账号存在33积分

**Comment by hongyangAndroid** [comment]
之前因为有过很多营销号肆意分享，临时给分享加了一个约束，50积分以上才可以分享。

这块有什么好的建议也可以提出~

**Comment by loper7** [comment]
嗷，感觉可以加一个tips提示
