### ISSUE TITLE
密码无法找回

### ISSUE THREAD

**Issue by zxcaz** [hongyangAndroid/wanandroid#261]
没发现 密码找回功能

**Comment by hongyangAndroid** [comment]
密码忘记了 可以给我邮箱 623565791@qq.com 发送下账号，已经密码大致记忆，或者填写的邮箱，我帮你重置。

**Comment by gitdecode** [comment]
洪洋哥，后期是否可以添加通过邮箱找回密码的功能

**Comment by hongyangAndroid** [comment]
@gitdecode 在考虑中呢，更想加入微信登录，受约一些条件，正在努力。
