### ISSUE TITLE
文章链接失效

### ISSUE THREAD

**Issue by gaolhjy** [hongyangAndroid/wanandroid#265]
标题为 《Android系统拍照及打开系统相册  完美适配Android 10,9,8,7,6,5,4》 这篇文章链接失效.
分享人: 深红骑士
分类: 广场Tab/广场
时间: 2020-06-17 23:30

提交人: 13871599512

**Comment by hongyangAndroid** [comment]
感谢反馈，已处理，后续可以直接点击这里反馈：
![image](https://user-images.githubusercontent.com/10704521/100204769-3eeb8680-2f3f-11eb-8abb-795a75fa0368.png)
