### ISSUE TITLE
提示分享失败，积分不足？没有地方查看积分，也不知道如何获取积分，没法用

### ISSUE THREAD

**Issue by czy1121** [hongyangAndroid/wanandroid#268]
rt

**Comment by hongyangAndroid** [comment]
因为之前遇到恶意分享，所以设置了50积分后才能分享。

积分的获取规则可以看这里：

https://wanandroid.com/blog/show/2653

正常情况下，连续登陆几天，或者经常分享文章，积分是足够哒。
