### ISSUE TITLE
公众号有些文章没有收录

### ISSUE THREAD

**Issue by loflv** [hongyangAndroid/wanandroid#270]
比如说：
1. 鸿神 12月14日 Google工程师给初学者的kotlin入门知识
2. 郭神的11月26日 Atrfactory、jetPack和mvvm该如何完美结合？
文章都没有收录

有的时候印象中看过一些文章但是细节记不得了，想去公众号里找，找了半天没找到，然后就发现有些文章没有收录了

**Comment by hongyangAndroid** [comment]
人工收录的，估计漏了，可以自己分享文章的，到时候站内可以搜索。



---原始邮件---
发件人: "loflv"<notifications@github.com&gt;
发送时间: 2020年12月23日(周三) 下午5:07
收件人: "hongyangAndroid/wanandroid"<wanandroid@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [hongyangAndroid/wanandroid] 公众号有些文章没有收录 (#270)




 
比如说：
  
鸿神 12月14日 Google工程师给初学者的kotlin入门知识 

郭神的11月26日 Atrfactory、jetPack和mvvm该如何完美结合？
 文章都没有收录 
 
有的时候印象中看过一些文章但是细节记不得了，想去公众号里找，找了半天没找到，然后就发现有些文章没有收录了
