### ISSUE TITLE
历史消息接口，fullLink 字段异常

### ISSUE THREAD

**Issue by ASCII13** [hongyangAndroid/wanandroid#284]
接口地址：
/message/lg/readed_list/1/json

问题截图：
![20210705155231](https://user-images.githubusercontent.com/8610206/124436936-1b2bd100-dda9-11eb-99c3-e602dd1e7dc8.jpg)

貌似只有 `"fromUser": "鸿洋"`, 会出现这种情况

**Comment by hongyangAndroid** [comment]
感谢反馈，已经修复~
