### ISSUE TITLE
发现一个Bug 在线工具bejson 

### ISSUE THREAD

**Issue by 852172891** [hongyangAndroid/wanandroid#29]
链接地址 ：http://www.wanandroid.com/tools/bejson

问题描述 ：输入内容为空时，点击 树形解析 ，下边出来 这些代码，应该是少了一个为空判断

Error: Parse error on line 1: ^ Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'EOF'

**Comment by hongyangAndroid** [comment]
恩恩，多谢，我们做一下空判断~
