### ISSUE TITLE
根据id获取文章信息的接口

### ISSUE THREAD

**Issue by moxiaov587** [hongyangAndroid/wanandroid#292]
感谢鸿洋大神的开放接口，我遇到一个文章`collect`状态的同步问题，我个人觉得在App端，将`collect`状态的获取放置在用户点击文章进入webview时应该可以减少大部分的同步问题，但是目前我在开放api的列表里没有找到可以通过文章的id来获取文章信息的接口，不知大神是否有类似的接口或者能否开放一个这样的接口，谢谢

**Comment by hongyangAndroid** [comment]
新增接口：

```
https://wanandroid.com//article/1110/info/json
```
1110 为文章 id，登录时访问，会填充 collect 状态，未登录始终为 false；

![WX20220306-171040](https://user-images.githubusercontent.com/10704521/156916609-1d75802b-f629-414a-bebe-0e7b42e259de.png)

**Comment by moxiaov587** [comment]
感谢鸿洋大神
