### ISSUE TITLE
多端账号收藏状态不同步

### ISSUE THREAD

**Issue by goweii** [hongyangAndroid/wanandroid#294]
比如我打开2个浏览器登录同一个账号，chrome里收藏一个文章，safari里刷新下还是未收藏状态，但是收藏列表倒是有的。
多app同样。

**Comment by hongyangAndroid** [comment]
确实存在这个问题，目前文章收藏的状态是通过sessionId作为key做了一层缓存，所以不同的回话会导致不同步。

后面我改成通过用户身份为key重新做下缓存设计，感谢反馈。

**Comment by hongyangAndroid** [comment]
尝试修复了多端缓存不一致的问题，欢迎体验反馈。

**Comment by goweii** [comment]
已验证OK
