### ISSUE TITLE
你好，请问这个api能用吗，现在看注册登录都失败了，地址还是这个不https://www.wanandroid.com/  注册登录Htt返回405

### ISSUE THREAD

**Issue by changlin0501** [hongyangAndroid/wanandroid#296]

**Comment by hongyangAndroid** [comment]
API可用，目前网站所用API和开放API是同一个。

405建议客户端排查下问题，大概率请求还没到Server端。

可以在github下载一个开源的wanandroid app体验便于辅助开发。

**Comment by changlin0501** [comment]
应该是登录和注册这两个API问题，其他接口可以拿到
![image](https://user-images.githubusercontent.com/47729295/162158346-282eb788-5944-4726-9522-4d9cca503540.png)
![image](https://user-images.githubusercontent.com/47729295/162158619-1319a0f6-0e68-4223-8c6e-e27e54bae71e.png)

**Comment by hongyangAndroid** [comment]
这个错误信息很明确呀，这两个接口都是仅支持POST的。

<img width="699" alt="image" src="https://user-images.githubusercontent.com/10704521/162160748-e3bf70c2-5b57-48a9-b8cd-5fbd35a7bc22.png">

浏览器默认访问method为GET。

**Comment by changlin0501** [comment]
好的，谢谢！我再找找原因
