### ISSUE TITLE
[Bug] 问答接口第0页和第1页返回重复数据

### ISSUE THREAD

**Issue by Lowae** [hongyangAndroid/wanandroid#297]
接口：https://wanandroid.com/wenda/list/0/json 
如:
https://wanandroid.com/wenda/list/0/json
https://wanandroid.com/wenda/list/1/json
会返回部分相同的数据

**Comment by hongyangAndroid** [comment]
这个接口page从 1 开始哈，0应该有奇奇怪怪的问题，我更新下api 文档。

**Comment by Lowae** [comment]
噢噢，原来是这样
