### ISSUE TITLE
搜索API出错了

### ISSUE THREAD

**Issue by jyygithub** [hongyangAndroid/wanandroid#305]
接口：https://www.wanandroid.com/article/query/0/json
方法：POST
参数：form-data，k=y
返回：500Internal Server Error

**Comment by hongyangAndroid** [comment]
![image](https://user-images.githubusercontent.com/10704521/226162054-f37c8d6c-1abb-41ce-8fb3-612c17dfdef5.png)
测试没发现问题呢
