### ISSUE TITLE
老哥好，我刚才发现调用搜索api，下拉加载更多数据时，服务器返回500

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [hongyangAndroid/wanandroid#306]
D/NET_LOG: com.drake.net.exception.ServerResponseException: 500 https://www.wanandroid.com/article/query/3/json ...(SearchResultActivity.kt:77)

![微信图片_20230417140057](https://user-images.githubusercontent.com/54784104/232398751-05a1e61c-6a2e-4168-a1dd-a5d98478958c.jpg)

**Comment by hongyangAndroid** [comment]
才发现有问题，已经修复，感谢反馈
