### ISSUE TITLE
网站问题反馈

### ISSUE THREAD

**Issue by LiMingzzz** [hongyangAndroid/wanandroid#36]
在搜索栏输入“Android 拍照自动识别手机号 | OCR”后报错
type Exception report

message Request processing failed; nested exception is org.hibernate.exception.SQLGrammarException: could not execute query

description The server encountered an internal error that prevented it from fulfilling this request.

exception

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.hibernate.exception.SQLGrammarException: could not execute query
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:894)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:778)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	com.zhy.xueandroid.web.SystemContextFilter.doFilter(SystemContextFilter.java:23)
	org.springframework.orm.hibernate3.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:198)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
root cause

**Comment by hongyangAndroid** [comment]
感谢反馈，在做非法字符过滤的时候，漏了“|”,导致SQL执行错误。

后续版本更新会修复。

**Comment by hongyangAndroid** [comment]
已修复~
