### ISSUE TITLE
取消收藏接口好像不管用了 ？

### ISSUE THREAD

**Issue by xks19943** [hongyangAndroid/wanandroid#37]
http://www.wanandroid.com/lg/uncollect/99/json
POST
参数：
    originId:1165，没有则写-1

我取消不了收藏 
谢谢

**Comment by xks19943** [comment]
然后用那个kotlin写的app也是调用失败  可能他和我一样将 99理解成了 id，然后originId写了 -1    我用 fiddler抓了下包  然后发现originId是id 路径里面的那个99对应就不知道是啥   谢谢鸿洋大神

**Comment by hongyangAndroid** [comment]
取消收藏一共有两个地方可以触发：

1. 文章列表

http://www.wanandroid.com/lg/uncollect_originId/2333/json

id传入的是列表中文章的id。

![image](https://user-images.githubusercontent.com/10704521/36082340-8038e836-0fe3-11e8-8a33-298c5d799d25.png)


2. 我的收藏页面（该页面包含自己录入的内容）

http://www.wanandroid.com/lg/uncollect/2805/json

id传入的是，我的收藏文章列表的id。

![image](https://user-images.githubusercontent.com/10704521/36082329-70c6f1e0-0fe3-11e8-947f-d7b298a8565a.png)

之前的文档有问题，已经更新。

**Comment by xks19943** [comment]
好的  明白了 谢谢
