### ISSUE TITLE
站内收藏文章以后返回json串中“collect”字段依然为false

### ISSUE THREAD

**Issue by onlyloveyd** [hongyangAndroid/wanandroid#38]

**Comment by hongyangAndroid** [comment]
感谢反馈，不过测试后未复现。

测试前提：**已登录**。

测试路径：

在首页点击一篇文章收藏：
![image](https://user-images.githubusercontent.com/10704521/36535149-b141038c-1803-11e8-8f9c-e42e15404292.png)

然后访问
[http://www.wanandroid.com/article/list/0/json](http://www.wanandroid.com/article/list/0/json)查看返回数据状态。

![image](https://user-images.githubusercontent.com/10704521/36535163-c284129c-1803-11e8-86ad-35c7db533962.png)

如果按照此路径仍有问题，跪求详细信息。

**Comment by onlyloveyd** [comment]
麻烦了，请求文章列表的时候没有添加cookie，所以出现了上面的问题，
谢谢指导
