### ISSUE TITLE
留下你的博客地址，加个友情链接吧

### ISSUE THREAD

**Issue by hongyangAndroid** [hongyangAndroid/wanandroid#39]
准备收集一波友情链接，如果您也写博客，不妨加个友链吧~~

友情链接页面：
[http://www.wanandroid.com/ulink](http://www.wanandroid.com/ulink)

![image](https://user-images.githubusercontent.com/10704521/36735831-128f3b24-1c12-11e8-8deb-ccac246ef5f7.png)

希望您是：

* 独立建站的博主
* 技术社区
* 类似wanandroid,极客导航这样的技术服务站点
* 等技术类

直接留言即可。

**Comment by hongyangAndroid** [comment]
http://www.jowanxu.top/

**Comment by xiaweizi** [comment]
http://xiaweizi.cn

**Comment by hongyangAndroid** [comment]
@xiaweizi 已经添加~~记得加一哈wanandroid哈~

**Comment by xiaweizi** [comment]
![image](https://user-images.githubusercontent.com/18526994/36842909-32d19e50-1d88-11e8-883a-a804eb67372f.png)

博客刚建号就已经添加进去了，还赞助了您的网站，哈哈，对我的帮助挺大的，虽然钱少。。。

**Comment by hongyangAndroid** [comment]
非常感谢~~~

**Comment by linzhengloser** [comment]
www.linzhengblog.com

**Comment by hongyangAndroid** [comment]
@linzhengloser 已添加~

**Comment by zhenghuiy** [comment]
http://huihui.name

**Comment by OCNYang** [comment]
[www.ocnyang.com](http://ocnyang.com/)  
连背景图片我都给自己准备好了，哈哈~~  
![http://obbu6r1mi.bkt.clouddn.com/ocnyang.png](http://obbu6r1mi.bkt.clouddn.com/ocnyang.png)

**Comment by hongyangAndroid** [comment]
@zhenghuiy @OCNYang 已添加~ 显示图不好看，可以给我传图~

**Comment by whatshappen** [comment]
http://blog.csdn.net/wangwasdf

**Comment by aaa106** [comment]
http://www.twodogs.top
友链已加

**Comment by monsterLin** [comment]
https://monsterlin.com/

**Comment by monsterLin** [comment]
φ(>ω<*) 翔哥，你的友链已置顶 @hongyangAndroid

**Comment by Shanlovana** [comment]
http://www.halloandroid.club/    多谢洋神  待会儿P好图将图片上传

**Comment by rangaofei** [comment]
https://rangaofei.github.io
稍后把我掘金的文章全都移植到我的博客上

**Comment by hongyangAndroid** [comment]
@aaa106 @monsterLin @Shanlovana @rangaofei 已添加~感谢各位支持，支持换图~~尺寸为474 * 180。

**Comment by hongyangAndroid** [comment]
@whatshappen csdn的就不加啦~这个主要针对个人博主，已有的为几个朋友~

**Comment by aaa106** [comment]
@hongyangAndroid 
http://www.twodogs.top/图片

**Comment by aaa106** [comment]
@hongyangAndroid  友链logo
![logo](https://user-images.githubusercontent.com/21004685/37075747-38bf7820-220e-11e8-8ad4-8f5dadee533c.png)

**Comment by WuXiaolong** [comment]
吴小龙同學：http://wuxiaolong.me/

**Comment by coding-dream** [comment]
编程之乐：coding-dream.github.io

**Comment by imtianx** [comment]
imtianx :http://imtianx.cn/

**Comment by coding-dream** [comment]
@hongyangAndroid 编程之乐：https://coding-dream.github.io/ 的logo：
![logo](https://user-images.githubusercontent.com/15939160/37131694-8f370874-22c4-11e8-9f53-9bb41b006ab6.png)

**Comment by WuXiaolong** [comment]
@hongyangAndroid 好的，吴小龙同學：http://wuxiaolong.me/ logo 如下：
![](http://7q5c2h.com1.z0.glb.clouddn.com/WuXiaolongBlogLogo.png)

**Comment by Dustray** [comment]
https://dustray.cn/
已加

**Comment by imtianx** [comment]
@hongyangAndroid ，imtianx 的博客：http://imtianx.cn 的logo如下：
![](http://img.imtianx.cn/imtianx_wanandroid_logo.png)

**Comment by hundred666** [comment]
https://txiner.top
在努力的学习，不知道能不能达到鸿洋大神的要求

**Comment by youlookwhat** [comment]
https://youlookwhat.github.io
友链很早之前就自己添加了😄

**Comment by hongyangAndroid** [comment]
@hundred666 @youlookwhat 已加

**Comment by BryantPang** [comment]
http://chihopang.top/ 
求蹭大佬一波热度...

**Comment by hongyangAndroid** [comment]
@BryantPang 已添加

**Comment by LouisShark** [comment]
http://ilouis.me/
友链已加
![image](https://user-images.githubusercontent.com/18005609/37637463-e871acbe-2c42-11e8-9c01-e52330fa939c.png)

**Comment by jixiaoyong** [comment]
季小勇的博客 http://jixiaoyong.github.io/blog/

厚着脸皮求大神一波友链，友链已加在菜单中。Thanks♪(･ω･)ﾉ

![logo](https://github.com/jixiaoyong/jixiaoyong.github.io/raw/master/images/blog/2018-03/bloglogo.png?raw=true)

**Comment by hongyangAndroid** [comment]
@Ivonhoe 已添加~

**Comment by hongyangAndroid** [comment]
@jixiaoyong 已添加，不过你的网站是不是挂了哇~~

**Comment by jixiaoyong** [comment]
谢谢大佬！
网站木有挂~ 截图为证哈O(∩_∩)O
托管在github.io上应该不会轻易狗带的
![](https://s1.ax1x.com/2018/03/25/9L8eJJ.png)

**Comment by hongyangAndroid** [comment]
@ziiai 已添加~~logo有点拉伸，最好尺寸为474 * 180。

**Comment by GcsSloop** [comment]
鸿洋大神，求一个友链。
网址： http://www.gcssloop.com
图片地址： http://www.gcssloop.com/assets/siteinfo/friends/wanandroid-flink.jpg

![](http://www.gcssloop.com/assets/siteinfo/friends/wanandroid-flink.jpg)

我的友链：http://www.gcssloop.com/friends

------

![](http://ww1.sinaimg.cn/large/005Xtdi2gy1fq7zsi4w7yj30gg0e877b.jpg)

**Comment by hongyangAndroid** [comment]
@onlyloveyd done~~ 文章很好~

**Comment by hongyangAndroid** [comment]
@GcsSloop 感谢~~~文章太赞~~已经添加~

**Comment by GcsSloop** [comment]
谢谢( ´▽｀) @hongyangAndroid

**Comment by ziiai** [comment]
鸿洋兄，链接logo正在重新设计，可否到时告知~



发自我的小米手机
在 张鸿洋 <notifications@github.com>，2018年4月13日 上午10:40写道：

@GcsSloop<https://github.com/GcsSloop> 感谢文章太赞已经添加~

**Comment by hongyangAndroid** [comment]
@ziiai 好了，直接在这回复就行。

**Comment by ziiai** [comment]
ok



发自我的小米手机
在 张鸿洋 <notifications@github.com>，2018年4月13日 上午11:15写道：

@ziiai<https://github.com/ziiai> 好了，直接在这回复就行。

**Comment by bboylin** [comment]
24号程序猿：[https://bboylin.github.io](https://bboylin.github.io)

**Comment by hongyangAndroid** [comment]
@bboylin @chendongMarch 已添加，感谢，PS:还可以自己提供配图~

**Comment by BigSweet** [comment]
博客地址: https://bigsweet.github.io/
友链：https://bigsweet.github.io/  在其他博客目录中
图片：http://wx1.sinaimg.cn/mw690/006jBEh3gy1fpa1ae27t1j30qn0qndgm.jpg
![image](https://user-images.githubusercontent.com/18210031/39284957-784524a2-4948-11e8-921c-7a717114e605.png)

**Comment by mzlogin** [comment]
鸿洋大神来友链走一波~

链接：<http://mazhuang.org>

图片：
![default](https://user-images.githubusercontent.com/1646590/39394008-e12ddb46-4afe-11e8-89ca-21ee8b533626.jpg)

wanandroid 的链接已加：<http://mazhuang.org/links/ >。

**Comment by hongyangAndroid** [comment]
@BigSweet @mzlogin 已添加~

**Comment by ziiai** [comment]
鸿洋兄，logo改的一直没啥点子~先简单按照格式要求走一波吧。
[极智能](http://www.ziiai.com)（www.ziiai.com）：
![logo_link_wanandroid](https://user-images.githubusercontent.com/25836484/39459050-6f562076-4d2b-11e8-9a78-0ef5943ef3f5.png)
有劳啦！

**Comment by BigSweet** [comment]
博客地址: https://bigsweet.github.io/
洋神，帮我换个图，我发现我的图片扁了。哈哈。麻烦啦
换图片为
https://raw.githubusercontent.com/BigSweet/Blog/master/logo.jpg

**Comment by hongyangAndroid** [comment]
@BigSweet @ziiai 搞定啦~

**Comment by TonnyL** [comment]
https://tonnyl.github.io/ 鸿阳大佬求➕😉

**Comment by hongyangAndroid** [comment]
@TonnyL 已添加~~

**Comment by itfengan** [comment]
http://www.fengan.info   🐑哥求加

**Comment by yasinasama** [comment]
http://yasina.me  哈哈，互粉

**Comment by hongyangAndroid** [comment]
@itfengan @yasinasama 已添加~

**Comment by hongyangAndroid** [comment]
@weijunzii 搞定~

**Comment by kwg520** [comment]
钢笔布莱恩特  https://github.com/kwg520

**Comment by hongyangAndroid** [comment]
@kwg520 done

**Comment by xujiaji** [comment]
洋神，申请个友链:laughing:
网站： https://blog.xujiaji.com/
logo：
![blog logo](https://user-images.githubusercontent.com/16447251/43031877-4fd0aaea-8cdd-11e8-9281-a93904b8ce66.png)

我的友链：https://blog.xujiaji.com/links

**Comment by zhanglihow** [comment]
加个友链 http://zhangliblog.top/

**Comment by hongyangAndroid** [comment]
@xujiaji @zhanglihow done

**Comment by FuZhucheng** [comment]
辅助：https://blog.csdn.net/Jack__Frost

**Comment by chendongMarch** [comment]
大神，上面的 cdevlab.top 帮我换一下吧，换成 http://zfyx.coding.me，图片 http://cdn1.showjoy.com/shop/images/20180821/WKTR4DMI2WW7619FQKBA1534815028733.png

**Comment by ThinkinLiu** [comment]
http://itlao5.com  
已经添加wanandroid.com友链到首页

**Comment by bao1zhi** [comment]
技术社区
名称：LiveVideoStack
连接 http://www.livevideostackcon.com/
logo 
![1](https://user-images.githubusercontent.com/20471490/45426363-9c80b900-b6ce-11e8-9671-1253030a9bee.jpg)

**Comment by z790704069** [comment]
网站名称：[考拉的网络日志][1]
网站地址：http://www.kooola.com
网站描述：在平凡的工作生活中，记录碎片化的知识和生活感悟
网站logo：![][2]

[1]: https://www.kooola.com
[2]: https://www.kooola.com/user/img/logo.png

**Comment by z790704069** [comment]
> 博客
> 名称:欧阳鹏
> 链接: https://blog.csdn.net/ouyang_peng
> 
> 已经添加wanandroid.com友链到首页

可以加波友链吗
网站名称：[考拉的网络日志][1]
网站地址：http://www.kooola.com
网站描述：在平凡的工作生活中，记录碎片化的知识和生活感悟
网站logo：![][2]

[1]: https://www.kooola.com
[2]: https://www.kooola.com/user/img/logo.png

**Comment by wtmsbaaa** [comment]
个人博客
名称：菜的抠jio
网站地址：https://www.caidekoujio.xyz/
logo
![logosc_7380421540260633](https://user-images.githubusercontent.com/35449960/47336797-ac26f080-d6c3-11e8-8f5b-249557f184ac.jpg)

**Comment by MRYangY** [comment]
可以加吗?
宇宝守护神:https://blog.csdn.net/qq_34902522

**Comment by sz136138** [comment]
[深圳PCBA加工](http://pcba.fandoukeji.top)

**Comment by sz136138** [comment]
可以交换一个友情链接吗
[深圳方案开发](http://www.doofdoo.cn)
http://www.doofdoo.cn

**Comment by sz136138** [comment]
一个有关于[方案开发](http://www.fandoukeji.cn)的博客  http://www.fandoukeji.cn

**Comment by sz136138** [comment]
[美容仪OEM加工](http://www.meirongyichangjia.cn)   http://www.meirongyichangjia.cn

**Comment by tinuv** [comment]
https://tinuv.me

**Comment by lxqxsyu** [comment]
加友链 https://dp2px.com  Android方向

**Comment by pengfeigao** [comment]
![blog](https://user-images.githubusercontent.com/9261499/52553764-a8101180-2e1f-11e9-8866-54a6fa64dbd5.png)
翔哥~求加友链！
个人博客：[http://www.imeina.cn](http://www.imeina.cn)

**Comment by z790704069** [comment]
已添加~





在 2019-02-11 16:10:42，"高鹏飞" <notifications@github.com> 写道：



翔哥~求加友链！
个人博客：http://www.imeina.cn

**Comment by maoqitian** [comment]
洋哥~求加友链！
>个人技术分析小站
名称：maoqitian
博客地址：[https://www.maoqitian.com/](https://www.maoqitian.com/)

- logo
![](https://github.com/maoqitian/MaoMdPhoto/raw/master/hexo%E5%8D%9A%E5%AE%A2%E6%90%AD%E5%BB%BA/mylogo.png)

**Comment by yanzhenjie** [comment]
已加到个人主页。

地址：  
[https://yanzhenjie.com](https://yanzhenjie.com)

图片：  
![严振杰](https://yanzhenjie.com/images/wanandroid.svg)

**Comment by AlanCheen** [comment]
程序亦非猿：

阿里巴巴资深无线开发工程师

地址：
http://yifeiyuan.me/

感谢~

**Comment by MRYangY** [comment]
https://rainyang.me/

**Comment by shijiacheng** [comment]
shijiacheng‘s blog
http://shijiacheng.studio

**Comment by fuusy** [comment]
hi 洋哥 
名称 ： SGoofy
博客地址  https://fuusy.github.io/
best regars!

**Comment by lxqxsyu** [comment]
> 加友链 https://dp2px.com Android方向

换个友链：

名称：水寒的博客
站点地址： https://dp2px.com
站点描述：Android/Java/Kotlin/前端/嵌入式/Python

**Comment by cheng2290** [comment]
名称：你我学习网
站点地址： https://www.niwoxuexi.com
站点描述：Android/Java/Kotlin/前端/嵌入式/Python/Web/小程序

**Comment by wenguan0927** [comment]
名称：陈文管的博客
地址：https://www.chenwenguan.com/

阿里巴巴高德高级无线开发

感谢~

**Comment by PBK-B** [comment]
名称：天真的小窝
站点地址：https://bin.zmide.com/

已添加 wanandroid ，刚成年的小白全栈工程师，看 wanandroid 半年来学到很多，也准备尽量坚持每天记录下自己学到的技术和自己的成长，谢谢啦

**Comment by jimmysuncpt** [comment]
名称：**Android 大强哥**
站点地址：https://jimmysun.blog.csdn.net/
已添加 wanandroid，感谢~

**Comment by jzj1993** [comment]
www.paincker.com
已添加 wanandroid，谢谢~

**Comment by LuoGuoXin** [comment]
https://androidguy.cn
安卓仔

**Comment by Android-Alvin** [comment]
https://www.jianshu.com/u/59a2002db85b Alvin老师

**Comment by jiulu313** [comment]
https://www.helloworld.net/
你好世界

谢谢

**Comment by VIPyinzhiwei** [comment]
昵称：殷志威的博客
简介：终身学习者
地址：https://vipyinzhiwei.com

感谢：）

**Comment by hongyangAndroid** [comment]
@VIPyinzhiwei 已加入，别忘了在合适的位置加上 wanandroid 哈~

**Comment by VIPyinzhiwei** [comment]
@hongyangAndroid OK~

**Comment by coding-dream** [comment]
昵称：Alien的小窝
简介：一个专攻于Android技术，视频剪辑，自媒体，个人成长，副业相关的小站
地址：[http://www.ssup.cc/](http://www.ssup.cc/)

> 备注：也欢迎其他朋友互换友链！

**Comment by wdmzjxzl** [comment]
title: HotList今日热榜开放API
link: https://api.zlinblog.cn/index

**Comment by cheng2290** [comment]
https://www.niwoxuexi.com/



在 2023-11-21 21:04:47，"Xu zl" ***@***.***> 写道：

title: HotList今日热榜开放API
link: https://api.zlinblog.cn/index
