### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by yeyueduxing** [hongyangAndroid/wanandroid#4]
1.希望添加搜索功能
2.希望网址页面可以自适应，毕竟现在移动设备浏览的很多啊
3.鸿神的目标是做一个安卓开发者必看的网站，那么个人之力毕竟有限，也可以让其他开发者添加数据，当然这也管理也就更麻烦了。
4.网站的定位和掘金，简书等技术网站重复性很强，可以有些特别的功能，单纯资讯技术网站还是很多的，竞争力不强。
5.在线工具这个蛮好的，但功能较少，鸿神也可以加些开发过程中常用的功能，例如GET，POST网络请求调试，AS虽然有这样的插件，但每次用都出问题。鸿神开发过程中肯定也有很多常用的东西，可以加到里面的。
上诉是我个人看法，希望鸿神的网站能越做越好

**Comment by hongyangAndroid** [comment]
非常感谢~
1、2、5都在计划中~ 2，5的前置需要账号体系，会尽快开发。
4的话，定位其实不是技术资讯流类，也不是希望做多么大的站点（对大家有点用就好），最终目标是按照Android体系结构划分分类文章。
3这个有过尝试，效果比较差，这个确实难保证~
