### ISSUE TITLE
后端代码开源吗？

### ISSUE THREAD

**Issue by kaku2015** [hongyangAndroid/wanandroid#40]
希望可以介绍一下服务器的选型等资源信息，可以对服务端开发新手有个参考😊

**Comment by hongyangAndroid** [comment]
本站大致信息：

机器：2G+2核+5Mb(一开始1Mb应该够了)
服务器：tomcat 7
后端：Spring MVC + Hibernate + Spring (喜欢Mybatis的可以替换掉Hibernate)
