### ISSUE TITLE
请问接口是否有打算添加Https的支持

### ISSUE THREAD

**Issue by Javen205** [hongyangAndroid/wanandroid#42]
证书可以使用Let's Encrypt
添加了Https 的支持微信小程序就可以玩起来了

期待...

**Comment by hongyangAndroid** [comment]
后面会添加https的支持~

不过小程序好像还不支持外链，网站中多数文章都是外链形式~~~

**Comment by Javen205** [comment]
@hongyangAndroid 如果是企业注册的小程序是支持`webview`组件的

**Comment by hongyangAndroid** [comment]
噢噢，后面先把https支持了。

**Comment by CaiJingLong** [comment]
https://kikt.tk/
我的网站用的证书是TrustAsia TLS RSA CA的
在https://console.cloud.tencent.com/ssl申请的 1年免费期 到期后理论上可以继续申请

我的域名本身没备案 https可以访问,80端口就被阿里云拦截了 用的dns验证 备案后的话用文件验证也可以

**Comment by hongyangAndroid** [comment]
@CaiJingLong 感谢建议。

**Comment by XuQK** [comment]
@hongyangAndroid  https还没有支持上吗，这几天练手写了个小程序，可惜没有https上不了线~
请问这个https在计划中吗鸿神

**Comment by CaiJingLong** [comment]
更简单的方案
如果没有太复杂的需求,直接用caddy替换nginx 直接支持https

**Comment by hongyangAndroid** [comment]
开发api已经支持https啦~
