### ISSUE TITLE
小小的建议

### ISSUE THREAD

**Issue by DinsonCat** [hongyangAndroid/wanandroid#44]
客户端想做数据缓存，没网的时候也可以看啦，也省流量

所以首页的文章，能不能像知乎一样，查指定时间之前的文章嘞

**Comment by hongyangAndroid** [comment]
这个可以直接做呀~~缓存下之前请求的json和图片就好了~

**Comment by DinsonCat** [comment]
回复这么快，棒棒哒

**Comment by DinsonCat** [comment]
我的设想是这样的，

第一天请求了2页，我缓存json，然后第二天后台更新文章后，我肯定是要重新请求第一页数据的，那第一天缓存的json就都失效了
但是呢，如果有像知乎这样的接口http://news-at.zhihu.com/api/4/section/2/before/{timestamp}
那我就可以在本地无时效的缓存所有的数据了（用数据库）
