### ISSUE TITLE
收藏报错

### ISSUE THREAD

**Issue by weiliushuai** [hongyangAndroid/wanandroid#46]
在做收藏模块的时候，总是报错，提示“请先登录”，我明明已经登录了，还是这样提示。根据接口要求，只传递了一个文章id，纠结了两天，实在是不知道怎么解决？请问鸿神和各位路过的道友，有没有遇到过这样的问题？改怎么解决？

**Comment by MatthewDevelop** [comment]
没有持久化登录的cookie吧

**Comment by weiliushuai** [comment]
登录状态我都保存到本地了，应该不是这个问题吧！

**Comment by hongyangAndroid** [comment]
提示“请先登录”，应该是cookie持久化的问题。

可以参考已有的项目：[https://github.com/search?utf8=%E2%9C%93&q=wanandroid&type=](https://github.com/search?utf8=%E2%9C%93&q=wanandroid&type=) .

**Comment by weiliushuai** [comment]
问题已经解决，确实是没有cookie持久化，配置retrofit2时。谢谢 @MatthewDevelop @hongyangAndroid
