### ISSUE TITLE
收藏文章的时候如何将用户和文章联系起来？

### ISSUE THREAD

**Issue by lucklyperson** [hongyangAndroid/wanandroid#47]
**6.2 收藏站内文章
http://www.wanandroid.com/lg/collect/1165/json
方法：POST
参数： 文章id，拼接在链接中。
注意链接中的数字，为需要收藏的id.**

这个接口只post文章id。想问一下后台是如何将用户和文章联系起来的。

**Comment by hongyangAndroid** [comment]
请求中携带了cookie，其中包含sessionId，后台会根据sessionId关联到具体用户。

**Comment by lucklyperson** [comment]
ok，谢谢
