### ISSUE TITLE
2.2 知识体系下的文章 接口返回数据异常

### ISSUE THREAD

**Issue by cuileikun** [hongyangAndroid/wanandroid#51]
2.2 知识体系下的文章 
http://www.wanandroid.com/article/list/0?cid=60
这个接口返回的数据怎么不是json格式的呢
debug发现返回的是html格式的？
求大神指点

**Comment by hongyangAndroid** [comment]
[http://www.wanandroid.com/article/list/0/json?cid=60](http://www.wanandroid.com/article/list/0/json?cid=60)

![image](https://user-images.githubusercontent.com/10704521/38617302-3ab03abc-3dc9-11e8-8c6e-1248db47d371.png)

**Comment by cuileikun** [comment]
好的，谢谢洋哥。
