### ISSUE TITLE
适配问题pixel 8.1系统

### ISSUE THREAD

**Issue by codeguyFred** [hongyangAndroid/wanandroid#53]
![791523628475_ pic_hd](https://user-images.githubusercontent.com/7608175/38739316-247e6850-3f67-11e8-98d2-1ec93d55cca2.jpg)

**Comment by hongyangAndroid** [comment]
这里主要是提出对 wanandroid.com 的建议和问题反馈。

对于某开源app的问题，请提issue到具体的项目。
