### ISSUE TITLE
卸载就安装不上了的bug

### ISSUE THREAD

**Issue by wbq501** [hongyangAndroid/wanandroid#54]
![fd37ca81-a81b-406e-8d18-663894468b67](https://user-images.githubusercontent.com/7636966/38766906-64743ec2-400b-11e8-9506-de127cd4dbc3.png)

$ adb shell am start -n "com.kdp.wanandroidclient/com.kdp.wanandroidclient.ui.LauncherActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Error while executing: am start -n "com.kdp.wanandroidclient/com.kdp.wanandroidclient.ui.LauncherActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.kdp.wanandroidclient/.ui.LauncherActivity }
Error type 3
Error: Activity class {com.kdp.wanandroidclient/com.kdp.wanandroidclient.ui.LauncherActivity} does not exist.
Error while Launching activity

运行代码在mate9  8.0系统上面会出现Leaks 这个。然后卸载其中一个WAndroid就没有了。再次运行就会出现这个错误。。。手机上已经找不到这个应用了，我反复切换用户多次运行才装上签名APP然后我又卸载了就又出现这个反复几次切换用户都没有安装成功。  
而且手机沉浸式状态栏的虚拟键盘栏也有问题。已经存在虚拟键盘下面了

我也在wanandroid群里面  749937855 成都-小王

**Comment by wbq501** [comment]
运行代码在mate9 8.0系统上面会出现Leaks 这个。然后卸载Leaks之后玩Android就没有了。再次运行就会出现这个错误。。。手机上已经找不到这个应用了，我反复切换用户多次运行才装上签名APP然后我又卸载了就又出现这个反复几次切换用户都没有安装成功。

**Comment by hongyangAndroid** [comment]
hi ~~ 你运行的是这个[https://github.com/kangdongpu/WanAndroid](https://github.com/kangdongpu/WanAndroid) 项目，在这个项目提issue。   

这个仓库是针对wanandroid网站的。
