### ISSUE TITLE
收藏文章接口问题

### ISSUE THREAD

**Issue by cuileikun** [hongyangAndroid/wanandroid#55]
明明已经登录成功了，在首页点击收藏文章调 收藏文章接口的时候还是提示：请先登录
下面两个接口都试着过了
“6.2 收藏站内文章接口” http://www.wanandroid.com/lg/collect/1165/json
 “6.3 收藏站外文章”  http://www.wanandroid.com/lg/collect/add/json
http://www.wanandroid.com/lg/collect/add/json
顺便麻烦洋哥指点一下哪些是站内文章哪些是站外文章吧！

**Comment by hongyangAndroid** [comment]
[see #37 ](https://github.com/hongyangAndroid/wanandroid/issues/37)

**Comment by cuileikun** [comment]
抱歉洋哥，没有看懂， see #37 这个是取消收藏的。
请问收藏文章是哪个接口呢？

**Comment by hongyangAndroid** [comment]
取消收藏都支持的，参考[http://www.wanandroid.com/blog/show/2](http://www.wanandroid.com/blog/show/2#21)

**Comment by threedeer** [comment]
好的  谢谢

**Comment by HelloEthanY** [comment]
为什么删除站外收藏不能删除呢？

**Comment by hongyangAndroid** [comment]
@HelloEthanY 都可以，api里面有描述，或者在网站收藏tab直接操作，观察网络。 网站和开放接口使用的同一个。

**Comment by HelloEthanY** [comment]
描述我都看了的，我调用了删除收藏，再请求收藏列表，之前删除的那个收藏还存在，这个原因是什么呢？
