### ISSUE TITLE
【开放API收集】

### ISSUE THREAD

**Issue by hongyangAndroid** [hongyangAndroid/wanandroid#58]
响应大家需求，本站增加收录所有可用API的章节，如果大家有使用过觉得不错的OpenApi，欢迎直接回复。

[目前已经收集的API](http://www.wanandroid.com/article/list/0?cid=349)

**Comment by zfman** [comment]
### 河南理工大学课程库API
>河南理工大学课程表对外开放接口，本数据基于河南理工大学官网公示的课程Excel表格，作者使用脚本将其录入到个人数据库中，现在开放出来，以供移动开发者交流学习使用

- 收录了河南理工大学2017-2018第二学期的全校课程库
- 23个学院、901个班级、5647个课程、20241条课程记录
- 蹭课功能
- 分享课程
- 扫码导入
- 无需账号登录

[https://github.com/zfman/api-demo/tree/master/timetable](https://github.com/zfman/api-demo/tree/master/timetable)


### 美景分享软件API
>一个依托于位置、好友等方式的周边美景分享软件的后台API

[https://github.com/zfman/api-demo/tree/master/scenery](https://github.com/zfman/api-demo/tree/master/scenery)

**Comment by maoruibin** [comment]
清单 API ，自己开发了清单软件-[柳叶清单](https://gudong.name/list/#/)，同时把 API 公开了出来，具体地址：

https://github.com/maoruibin/liuye

**Comment by yh131412** [comment]
JSON API免费接口（各种提供JSON格式数据返回服务网站的API接口）
http://www.bejson.com/knownjson/webInterface/

**Comment by yh131412** [comment]
JSON API免费接口（各种提供JSON格式数据返回服务网站的API接口）
http://www.bejson.com/knownjson/webInterface/

**Comment by MZCretin** [comment]
免费开放api，已经维护一年多了
主页：https://www.mxnzp.com

**Comment by hongyangAndroid** [comment]
@MZCretin 赞，收录一下~

**Comment by wdmzjxzl** [comment]
HotList 今日热榜API：https://api.zlinblog.cn/index

收录全网热榜数据的api
