### ISSUE TITLE
来个竞赛呗

### ISSUE THREAD

**Issue by LillteZheng** [hongyangAndroid/wanandroid#6]
搞移动开发的，第三方API接口，用着用着就被和谐了，所以我觉得网站可以把接口提供出来，我们来做移动端，搞个竞赛，这样出来能让我们练练手，也可以提高网站知名度吗，我觉得ok

另外，网站除了android的知识，也可以添加一些后台的知识进来，比如搭建自己的服务器等等，
最后，大神的视频链接怎么不贴上去啊，那么好的教学资源，23333~~~~

**Comment by hongyangAndroid** [comment]
哈 ~ 刚上线，担心后台数据会发生变化，等基础功能稳定了会开发API的~

**Comment by hongyangAndroid** [comment]
[Open API](http://www.wanandroid.com/blog/show/2)已经上线！
