### ISSUE TITLE
我觉得应该添加一个注销登录功能

### ISSUE THREAD

**Issue by liubailin2017** [hongyangAndroid/wanandroid#63]
要不然sessionid泄露了，都没法注销登录

**Comment by hongyangAndroid** [comment]
![image](https://user-images.githubusercontent.com/10704521/39670224-8995a276-5132-11e8-9213-353aeb19fba2.png)

可以访问该接口，网页直接点击即可注销登录。

**Comment by liubailin2017** [comment]
谢谢你的回复， 开放api中没写注销api  http://www.wanandroid.com/blog/show/2

**Comment by hongyangAndroid** [comment]
```
https://www.wanandroid.com/user/logout/json

方法：GET
```
