### ISSUE TITLE
取消收藏接口有点问题 

### ISSUE THREAD

**Issue by SmallSmallrui** [hongyangAndroid/wanandroid#66]
取消了收藏以后 , 刷新文章列表,但是 文章上还是显示被收藏

**Comment by hongyangAndroid** [comment]
hi ~ 测试后并未复现该问题。

可以按照[#38](https://github.com/hongyangAndroid/wanandroid/issues/38)回答的方式，直接在浏览器上测试。

收藏和取消收藏，开放调用的接口，和在浏览器上使用的一致。
