### ISSUE TITLE
导航添加网址建议

### ISSUE THREAD

**Issue by cllstudy** [hongyangAndroid/wanandroid#67]
下面这些网址只是建议:
腾讯吐个槽:一站式解决用户反馈问题,可以微信回复以及接收回复:https://tucao.qq.com
腾讯文档:https://docs.qq.com
阿里文档--语雀:https://yuque.com
两个文档各有优缺点
pdf派;20个pdf在线工具,文档互转:https://www.pdfpai.com/
视频转gif,gif优化等(感觉这个很有用,很多在github上不会制作gif可以用这个)https://ezgif.com/
图片背景透明:http://www.aigei.com/bgremover/

**Comment by hongyangAndroid** [comment]
非常感谢。

添加了反馈栏目：收录了腾讯吐槽。
添加了在线文档：收录了腾讯文档和阿里文档。

剩下3个都添加到常用工具了。
