### ISSUE TITLE
支持一下

### ISSUE THREAD

**Issue by reallyzhang** [hongyangAndroid/wanandroid#7]
1，首页常用网址stackoverflow点击之后的跳转路径不对哈；
2，首页布局有点单调，可以考虑用大图片轮播图的首页顶部；
3，就目前,而言首页滑动右侧很空，可以考虑常用工具或者常用网址在页面滑动的时候可以常驻右侧；
4，既然是玩android，可以考虑将Android里面的布局风格和特效做在网页上，标新立异；

**Comment by hongyangAndroid** [comment]
感谢~
1.fixed~
2,3考虑中~~
4的难度比较大~~到时候看看在手机版本上做个md风格的把~
