### ISSUE TITLE
405 Not Allowed 

### ISSUE THREAD

**Issue by wangxp423** [hongyangAndroid/wanandroid#71]
07-02 11:45:51.722 16252-16319/com.xp.wanandroid V/RetrofitHelper: OkHttp: --> POST http://wanandroid.com/user/login http/1.1
    OkHttp: Content-Type: application/x-www-form-urlencoded
    OkHttp: Content-Length: 47
07-02 11:45:51.723 16252-16319/com.xp.wanandroid V/RetrofitHelper: OkHttp: 
    OkHttp: 
    OkHttp: --> END POST (47-byte body)
07-02 11:45:51.941 16252-16319/com.xp.wanandroid V/RetrofitHelper: OkHttp: <-- 405 Not Allowed http://www.wanandroid.com/user/login (217ms)
    OkHttp: Server: marco/2.2
    OkHttp: Date: Mon, 02 Jul 2018 03:45:49 GMT
07-02 11:45:51.942 16252-16319/com.xp.wanandroid V/RetrofitHelper: OkHttp: Content-Type: text/html;charset=utf-8
    OkHttp: Content-Length: 1045
    OkHttp: Connection: keep-alive
    OkHttp: X-Source: C/405
    OkHttp: Content-Language: en
    OkHttp: Allow: POST
    OkHttp: X-Request-Id: 7084fb3ea944983a7fbea9494c775ec7
    OkHttp: Via: S.mix-js-czx-108, T.108.D, V.mix-js-czx-106, T.71.D, M.ctn-js-taz2-067
07-02 11:45:51.980 16252-16319/com.xp.wanandroid V/RetrofitHelper: OkHttp: 
    OkHttp: <html><head><title>Apache Tomcat/7.0.77 - Error report</title><style></style> </head><body><h1>HTTP Status 405 - Request method 'GET' not supported</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Request method 'GET' not supported</u></p><p><b>description</b> <u>The specified HTTP method is not allowed for the requested resource.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.77</h3></body></html>
    OkHttp: <-- END HTTP (1045-byte body)
07-02 11:45:52.002 16252-16252/com.xp.wanandroid W/System.err: retrofit2.HttpException: HTTP 405 Not Allowed
        at com.jakewharton.retrofit2.adapter.kotlin.coroutines.experimental.CoroutineCallAdapterFactory$BodyCallAdapter$adapt$2.onResponse(CoroutineCallAdapterFactory.kt:104)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:123)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-02 11:45:52.003 16252-16252/com.xp.wanandroid W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
07-02 11:45:52.003 16252-16252/com.xp.wanandroid V/Test: loginFail = HTTP 405 Not Allowed
07-02 11:45:52.091 16252-16307/com.xp.wanandroid V/RenderScript: 0x55950cea40 Launching thread(s), CPUs 8

上面是异常，是这样的，我在用网站API，前两天调用的接口都一切正常，本周一来了以后，突然登录接口和搜索接口出现了以上异常，不能调用成功，请问是什么情况，而且我在用postman测试的时候是，正常的，但是用APP调用就各种不行，但是前两天又是好的，还请指点。

**Comment by hongyangAndroid** [comment]
从日志上看，好像登录使用了get 请求；登录接口对应的是post。

最近没有更新过这两个接口，如果postman 正常的话，check 下代码，是不是哪里导致requestMethod 变化了。

**Comment by wangxp423** [comment]
/**
     * 登录
     * @param username username
     * @param password password
     * @return Deferred<LoginResponse>
     */
    @FormUrlEncoded
    @POST("/user/login")
    fun loginWanAndroid(
            @Field("username") username: String,
            @Field("password") password: String
    ): Deferred<UserEntity>

请求用的post。我用kotlin写的，请求用的retorift2，除了登录和搜索其他接口都还能调用，好奇怪啊。我现在是一脸懵逼。

**Comment by hongyangAndroid** [comment]
我又思考了下，可能是 CDN 的问题，我现在把 CDN 切掉了，可以再试下。

**Comment by wangxp423** [comment]
试了也不行，我还用了我以前项目中用okhttp封装的网络请求代码试了下 也不行。目前还没有找到原因。

**Comment by hongyangAndroid** [comment]
发现问题了，我上周做了一件事，把wanandroid.com 访问的url 直接301到 www.wanandroid.com 了；

导致post 的登录请求，被301成 GET，从而导致405。

可以先使用 http://www.wanandroid.com ， 避免使用 http://wanandroid.com

我一会回退掉这次更新。

**Comment by hongyangAndroid** [comment]
已经上线~ 都支持了，欢迎再测一下。

**Comment by wangxp423** [comment]
试了，已经可以用了。给力！！！
