### ISSUE TITLE
要不要考虑增加一个提问功能

### ISSUE THREAD

**Issue by mrqinshou** [hongyangAndroid/wanandroid#72]
洋神可不可以加一个提问版块呀，悬赏提问，小弟有时候有些困惑是度娘不容易搜到的，苦于找不到大神传道受业解惑。。。也没有发现那个平台提问比较好一点，所以你的网站要不要考虑一下这个功能呢？

**Comment by hongyangAndroid** [comment]
提问版块容易加，回答问题的人找不到哇，我也木有办法投入各种激励机制。
