### ISSUE TITLE
登陆状态明文传输么？

### ISSUE THREAD

**Issue by BobEve** [hongyangAndroid/wanandroid#79]
鸿神，如题cookie需要加密后发送么，现在是明文传输吧

**Comment by hongyangAndroid** [comment]
恩 目前是明文。 

已经准备切为 token 方案了，还在测试中，现在的cookie 里面应该多了个 token，准备移除password，后续登录成功后用户信息也会屏蔽掉密码相关。

需要兼顾原有的项目，需要测试一段时间...

**Comment by chuwe1** [comment]
可以增加一个注销用户的接口啊，不然测试的用户会越来越多。鸿神库里面可能会存在很多的垃圾用户哦。相信广大码农们会很乐意在每次调试完注册接口后，注销刚注册的用户的...........
