### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by jianghaijun** [hongyangAndroid/wanandroid#8]
建议加个文章搜索功能

**Comment by hongyangAndroid** [comment]
已经开发完成啦，正在测试，预计周五上线，欢迎到时候体验下，提意见~~感谢~

**Comment by jianghaijun** [comment]
ok

**Comment by xiaoshengyufeng** [comment]
换了好几个名字注册，都没成功，出现Control character in cookie value or attribute.
用户超过6个字了。
再点注册提示“用户名已被注册”。登陆也出现这个“Control character in cookie value or attribute.”
表示登不进去，很无奈

**Comment by hongyangAndroid** [comment]
已知bug，用户名输入中文时发生。
用户名用字母或者数字吧
周末会修复。

**Comment by hongyangAndroid** [comment]
中文作为用户名已经修复~~感谢反馈~
