### ISSUE TITLE
ADD 速查 栏目

### ISSUE THREAD

**Issue by hongyangAndroid** [hongyangAndroid/wanandroid#80]
wanandroid 增加了速查栏目，意在为大家提供平时常用的内容查询：

[速查一切](http://www.wanandroid.com/article/query?k=%E9%80%9F%E6%9F%A5)

![image](https://user-images.githubusercontent.com/10704521/44614015-b5284c80-a84f-11e8-92ea-66cff0b00a19.png)

如果想要添加你经常查询的内容，可以给我们留言。

如果你想要帮助我们，也非常欢迎提供编写好的markdown 的稿件，我们会永久保持你的署名。

**Comment by Moosphan** [comment]
- Android studio快捷键
- Android studio常用插件
- Android面试大全
- Android常见知识点框架汇总
- Android疑难杂症分类
- Android开发必备书籍推荐
- Android 架构思想
- Android 今日头条
- Android 跨平台开发相关
- 用kotlin开发Android系列
- 代码封装、重构、扩展等思想
- Android开发习惯养成

暂时想到这些，后面想到再补充😄
