### ISSUE TITLE
大佬，发现一个小问题

### ISSUE THREAD

**Issue by CoderLengary** [hongyangAndroid/wanandroid#83]
当我更新一个todo为已完成状态，用的是http://www.wanandroid.com/lg/todo/update/[id]/json，
id: 不变
title: 不变
content: 不变
date: 不变
status: 0 // 改为1
type: 不变
这样返回的结果是对的，status变为1了，但是Completed date和completeDateStr皆为null

**Comment by hongyangAndroid** [comment]
看了下代码确实有这个问题。

更新状态可以先用：`/done/{id}/json` 。 

周末 fix.
