### ISSUE TITLE
ERR_INCOMPLETE_CHUNKED_ENCODING

### ISSUE THREAD

**Issue by salmanit** [hongyangAndroid/wanandroid#84]
www.wanandroid.com unexpectedly closed the connection.
ERR_INCOMPLETE_CHUNKED_ENCODING
我模拟器是有网络的，我现在用的模拟器自带的浏览器，网站也打不开，谁知道可能啥原因吗，这个网址应该也没被禁掉啊，我电脑都可以访问的。
而且我记得我以前模拟器是可以访问的，我以前运行过这个接口的app，奇了怪了。

**Comment by salmanit** [comment]
> 09-03 01:32:05.021 3110-3134/com.charliesong.wanandroid D/OkHttp: <-- 200 OK http://www.wanandroid.com/project/tree/json (3498ms)
09-03 01:32:05.021 3110-3134/com.charliesong.wanandroid D/OkHttp: Server: Apache-Coyote/1.1
09-03 01:32:05.021 3110-3134/com.charliesong.wanandroid D/OkHttp: Set-Cookie: JSESSIONID=FF9F32F47D68F8B98A5E3394E7356821; Path=/; HttpOnly
09-03 01:32:05.021 3110-3134/com.charliesong.wanandroid D/OkHttp: Content-Type: application/json;charset=UTF-8
09-03 01:32:05.021 3110-3134/com.charliesong.wanandroid D/OkHttp: Date: Mon, 03 Sep 2018 01:31:58 GMT
09-03 01:32:05.021 3110-3134/com.charliesong.wanandroid D/OkHttp: X-Cache: MISS from SD-Endian5.magellangps.com
09-03 01:32:05.021 3110-3134/com.charliesong.wanandroid D/OkHttp: X-Cache-Lookup: MISS from SD-Endian5.magellangps.com:8080
09-03 01:32:05.021 3110-3134/com.charliesong.wanandroid D/OkHttp: Transfer-Encoding: chunked
09-03 01:32:05.021 3110-3134/com.charliesong.wanandroid D/OkHttp: Via: 1.1 SD-Endian5.magellangps.com (squid/3.4.14)
09-03 01:32:05.021 3110-3134/com.charliesong.wanandroid D/OkHttp: Connection: keep-alive
09-03 01:32:05.021 3110-3134/com.charliesong.wanandroid D/OkHttp: Cache-Control: public, max-age=5
现在模拟器上所有接口都返回一个java.io.EOFException
我所有的接口请求都成了这个了，模拟器上的，不知道模拟器咋了，以前都好好的，我以前还在模拟器上测试过，最近也没改。 模拟器我以为是版本问题，可我试了19的，27，28的都不行。。
我在测试机上是正常的。

**Comment by hongyangAndroid** [comment]
不太清楚...
