### ISSUE TITLE
鸿洋大大玩Android能加上郭霖公众号文章集合么？

### ISSUE THREAD

**Issue by YumikoAzu** [hongyangAndroid/wanandroid#85]

**Comment by hongyangAndroid** [comment]
可以呀  不过手工一个个录 太费时间了。 有兴趣研究下微信文章抓取么，或者等我有空看看吧。

**Comment by mifenfeifen** [comment]
@hongyangAndroid 请教一下，请问您是通过搜狗抓取，还是代理获得key&app_token之后抓取？
亦或是绕过了这些麻烦的步骤？
