### ISSUE TITLE
鸿神，首页置顶的数据接口没有开放吗？

### ISSUE THREAD

**Issue by iceCola7** [hongyangAndroid/wanandroid#86]

**Comment by hongyangAndroid** [comment]
[http://www.wanandroid.com/article/top/json](http://www.wanandroid.com/article/top/json )

已经添加~~

感谢支持，不过置顶数据里面可能有广告，别有不愉快哟~~~

**Comment by iceCola7** [comment]
不会的 ^_^

**Comment by iceCola7** [comment]
@hongyangAndroid 我在网页端收藏了置顶的文章，[http://www.wanandroid.com/article/top/json](http://www.wanandroid.com/article/top/json)接口数据中 collect 一直是 false，这是怎么回事啊？在请求接口的时候 cookie 是没问题的。

**Comment by hongyangAndroid** [comment]
测了下是个 Bug...马上修复

**Comment by hongyangAndroid** [comment]
已修复 @iceCola7

**Comment by iceCola7** [comment]
好的，速度好快啊！
