### ISSUE TITLE
【意见收集】 关于公众号 tab

### ISSUE THREAD

**Issue by hongyangAndroid** [hongyangAndroid/wanandroid#87]
你可以在这里关于公众号tab 的建议，tab，或者你想要收录的公众号。

**Comment by rcj60560** [comment]
@hongyangAndroid 注册登录之后 能给用户设置个头像地址吗 ：）

**Comment by canyie** [comment]
@hongyangAndroid 申请收录公众号：码农翻身 程序员小灰
