### ISSUE TITLE
首页bannner字段问题

### ISSUE THREAD

**Issue by rcj60560** [hongyangAndroid/wanandroid#89]
首页bannner
http://www.wanandroid.com/banner/json
其中公众号id 都是不变的吗
我想固定拿到

desc : ""
id : 18
imagePath : "http://www.wanandroid.com/blogimgs/00f83f1d-3c50-439f-b705-54a49fc3d90d.jpg"
isVisible : 1
order : 1
title : "公众号文章列表强势上线"
type : 0
url : "http://www.wanandroid.com/wxarticle/list/408/1"

id 字段

**Comment by rcj60560** [comment]
@hongyangAndroid  : )

**Comment by hongyangAndroid** [comment]
获取公众号列表

```
http://wanandroid.com/wxarticle/chapters/json  
方法： GET
```
可以通过这个接口拿到呢。

其他的公众号数据接口参考open api 更新部分即可。
