### ISSUE TITLE
一点小小的建议

### ISSUE THREAD

**Issue by Colaman0** [hongyangAndroid/wanandroid#9]
玩Android网站收集了很多博文，我觉得如果能把公众号里的文章作为一个栏目加进去会很方便，因为原本在手机上查找自己需要的有时候要滑很久才能找到，如果能在玩安卓里看到跟公众号里的文章就很棒了，虽然现在也能找到，但是想找公众号里其他的文章还是不太方便

**Comment by hongyangAndroid** [comment]
恩恩，这个有考虑，本来想将一些大V的公众号做一个tab收录的，后来发现技术上挺难搞定的~~再研究下~~

对于我的公众号文章，可以在这里看到全部：

[https://github.com/hongyangAndroid/hongyangWeixinArticles/](https://github.com/hongyangAndroid/hongyangWeixinArticles/)

**Comment by ttxxly** [comment]
可以增加 RSS订阅吗

**Comment by Leo00001** [comment]
没有文章评论
