### ISSUE TITLE
登录失效问题

### ISSUE THREAD

**Issue by youlookwhat** [hongyangAndroid/wanandroid#95]
http://www.wanandroid.com/banner/json
这个接口过一段时间会返回cookie，但不是每次都返回，返回的cookie会覆盖之前登录的cookie，导致登录失效。

"banner/json"返回的cookie:
```java
<-- 200 OK http://www.wanandroid.com/banner/json (203ms)
11-09 15:13:38.709 7243-7285/com.example.jingbin.cloudreader D/OkHttp: Server: Apache-Coyote/1.1
11-09 15:13:38.709 7243-7285/com.example.jingbin.cloudreader D/OkHttp: Set-Cookie: JSESSIONID=23BC030B1A298CD45BC8FB148429658A; Path=/; HttpOnly
```
登录返回的cookie:
```java
Set-Cookie: JSESSIONID=74B03B4D0BB09A4F62F64770474260AF; Path=/; HttpOnly
Set-Cookie: loginUserName=jingbin; Expires=Sun, 09-Dec-2018 07:19:27 GMT; Path=/
```
JSESSIONID的值覆盖后登录会失效。
暂时在SM-G9550 系统8.0.0出现。

:-D

**Comment by hongyangAndroid** [comment]
我需要思考下... JSESSIONID应该每隔半小时就失效了。

不过banner/json的接口应该不会返回token_pass和loginUserName（登录和注册接口返回），即使JSESSIONID失效，这两个字段带上，也会自动登录。

可以帮忙测试下：

1. 当出现这种情况的时候，cookie中是否还包含：token_pass和loginUserName；
2. 访问任何需要登录的接口，例如收藏，携带token_pass和loginUserName是否能够正常收藏（可以用postman）；

**Comment by hongyangAndroid** [comment]
已经定位到问题...

前几天给密码脱敏，导致cookie 失效了...

目前已经修复。

发现 tokenpass= 9ac6cbb4bf50c79f6c735526e2180d66 

均为受到此bug 影响。

**Comment by hongyangAndroid** [comment]
非常感谢反馈！

**Comment by youlookwhat** [comment]
这边已经好了，感谢鸿扬大大提供接口供我们学习😄
