### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by suchen2** [hongyangAndroid/wanandroid#96]
鸿神，TODO工具能新增一个类似于一加手机的备忘录功能吗？
该功能可以添加一个选择框，可以删除已存在的内容(在原内容上文字中间添加一条删除的标记线，然后整体变灰色)。平时做一些待办事项和借还用。
TODO工具里的那个代办功能点击后，除了列表收起没有其他反应，不知道是不是设计如此，偶尔滑到“学习”，下面的FloatActionButton也不出来了

**Comment by hongyangAndroid** [comment]
恩 我主要负责添加 OpenAPI呢，你反馈的应该是某个版本开源app 的问题，需要在开源作者那里反馈。

如果需要添加什么接口，可以告诉我。
